"use client";

import { useCorporateContract } from "@/lib/queries/employer-accounts";
import { useEmployerInvoices } from "@/lib/queries/employer-invoices";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { koboToNaira } from "@tarragon/shared";

const BILLING_MODEL_LABEL: Record<string, string> = {
  per_employee: "Per employee",
  per_active_member: "Per active member",
  fixed_contract: "Fixed contract",
  service_based: "Service-based",
  hybrid: "Fixed + per active member",
};

const INVOICE_STATUS_BADGE: Record<string, { variant: "green" | "grey" | "amber" | "red"; label: string }> = {
  draft: { variant: "grey", label: "Draft" },
  issued: { variant: "amber", label: "Issued" },
  paid: { variant: "green", label: "Paid" },
  void: { variant: "grey", label: "Void" },
};

function nairaAmount(kobo: number): string {
  return `₦${koboToNaira(kobo).toLocaleString("en-NG", { maximumFractionDigits: 2 })}`;
}

/** Module 26 §26.15 — read-only for the employer, see employer_invoices_select
 * / corporate_contracts_select_institution_admin. Generation and status
 * changes are Tarragon-finance-only. */
export function EmployerBillingPanel({ organisationId }: { organisationId: string }) {
  const contract = useCorporateContract(organisationId);
  const invoices = useEmployerInvoices(organisationId);

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Contract terms</CardTitle>
          <CardDescription>Set by Tarragon; you can read but not change these here.</CardDescription>
        </CardHeader>
        <CardContent>
          {contract.data ? (
            <dl className="grid gap-3 text-sm sm:grid-cols-2">
              <div>
                <dt className="text-xs uppercase text-charcoal-ink/50">Billing model</dt>
                <dd className="text-charcoal-ink">
                  {contract.data.billing_model ? BILLING_MODEL_LABEL[contract.data.billing_model] : "Not set"}
                </dd>
              </div>
              <div>
                <dt className="text-xs uppercase text-charcoal-ink/50">Rate</dt>
                <dd className="text-charcoal-ink">
                  {contract.data.billing_rate_kobo != null ? `${nairaAmount(contract.data.billing_rate_kobo)} per person` : "—"}
                </dd>
              </div>
              <div>
                <dt className="text-xs uppercase text-charcoal-ink/50">Fixed amount</dt>
                <dd className="text-charcoal-ink">
                  {contract.data.billing_fixed_amount_kobo != null
                    ? nairaAmount(contract.data.billing_fixed_amount_kobo)
                    : "—"}
                </dd>
              </div>
              <div>
                <dt className="text-xs uppercase text-charcoal-ink/50">Billing interval</dt>
                <dd className="text-charcoal-ink">{contract.data.billing_interval ?? "—"}</dd>
              </div>
            </dl>
          ) : (
            <p className="text-sm text-charcoal-ink/60">No active contract yet.</p>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Invoices</CardTitle>
          <CardDescription>Generated by Tarragon finance from your contract each billing period.</CardDescription>
        </CardHeader>
        <CardContent>
          {(invoices.data ?? []).length === 0 ? (
            <p className="text-sm text-charcoal-ink/60">No invoices yet.</p>
          ) : (
            <ul className="divide-y divide-charcoal-ink/10">
              {(invoices.data ?? []).map((inv) => {
                const statusMeta = INVOICE_STATUS_BADGE[inv.status] ?? { variant: "grey" as const, label: inv.status };
                return (
                  <li key={inv.id} className="flex items-center justify-between gap-2 py-2">
                    <div>
                      <p className="text-sm text-charcoal-ink">
                        {inv.period_start} – {inv.period_end}
                      </p>
                      <p className="text-xs text-charcoal-ink/60">
                        {BILLING_MODEL_LABEL[inv.billing_model] ?? inv.billing_model}
                        {inv.headcount_basis != null && ` · ${inv.headcount_basis} people`}
                      </p>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="text-sm font-medium text-charcoal-ink">{nairaAmount(inv.amount_kobo)}</span>
                      <Badge variant={statusMeta.variant}>{statusMeta.label}</Badge>
                    </div>
                  </li>
                );
              })}
            </ul>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
