import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { VaccinationStatus } from "@/lib/rules/vaccination-status";

export interface SchoolHealthSummaryVaccineRow {
  name: string;
  status: VaccinationStatus;
  dosesGiven: number;
  lastDoseDate: string | null;
}

export interface SchoolHealthSummaryData {
  patientName: string;
  dateOfBirth: string | null;
  sex: "male" | "female" | null;
  generatedAt: string;
  vaccines: SchoolHealthSummaryVaccineRow[];
}

/**
 * Child Health Platform §48.12 ("school-related health... without giving
 * schools unrestricted medical-record access"). Resolved as a PRINTABLE
 * EXPORT the parent generates and hands to a school themselves — the school
 * never gets an account or any access to the platform at all, so none of the
 * institutional-access questions a school LOGIN would raise (what a school
 * account even is, aggregate-vs-individual access — see CLAUDE.md's I9
 * guardrail) apply here. See docs/PEDIATRIC_CHILD_HEALTH_SPEC.md.
 *
 * Deliberately narrow — vaccination status ONLY. Two things a school summary
 * must NOT be, on purpose:
 *   - It is not the Health Passport (lib/health-passport/health-passport-document.tsx),
 *     which is a full clinical summary (vitals, labs) meant for another
 *     doctor, not a school.
 *   - It does not include developmental screening results. A screening flag
 *     is a routing signal for a doctor (§48.5's own "not a diagnosis"), and
 *     surfacing it to a school risks stigmatising a child over an unvalidated,
 *     non-normed starter questionnaire (see that migration's header) — a
 *     categorically different kind of harm than "a school knows a vaccine
 *     status," which is exactly the evidence schools legitimately require.
 * "Health certificates" (a doctor's fitness-to-attend attestation) and formal
 * "health assessments" are NOT covered by this document — those need a real
 * clinician sign-off workflow, not a same-shape bundling-in here. See the
 * spec doc's deferred list.
 */

const VACCINATION_STATUS_LABEL: Record<VaccinationStatus, string> = {
  up_to_date: "Up to date",
  due: "Due",
  overdue: "Overdue",
  not_yet_due: "Not yet due",
  not_applicable: "Not applicable",
};

const styles = StyleSheet.create({
  page: { padding: 34, fontSize: 10, color: "#12324B", lineHeight: 1.4 },
  brand: { fontSize: 12, fontWeight: 700, color: "#0E7C52" },
  title: { fontSize: 18, fontWeight: 700, lineHeight: 1.2, marginTop: 6, marginBottom: 4 },
  subtitle: { fontSize: 10, color: "#555", marginBottom: 14 },
  section: { marginBottom: 12 },
  sectionTitle: { fontSize: 12, fontWeight: 700, marginBottom: 5, color: "#0E7C52" },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
    borderBottomWidth: 0.5,
    borderBottomColor: "#ddd",
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#12324B",
    fontWeight: 700,
  },
  col1: { width: "45%" },
  col2: { width: "20%" },
  col3: { width: "35%" },
  footer: { marginTop: 20, fontSize: 8, color: "#777", lineHeight: 1.4 },
});

export function SchoolHealthSummaryDocument({ data }: { data: SchoolHealthSummaryData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.brand}>TarragonHealth</Text>
        <Text style={styles.title}>School health summary</Text>
        <Text style={styles.subtitle}>
          {data.patientName}
          {data.dateOfBirth ? ` · DOB ${new Date(data.dateOfBirth).toLocaleDateString()}` : ""}
          {data.sex ? ` · ${data.sex}` : ""}
        </Text>
        <Text style={styles.subtitle}>
          Generated {new Date(data.generatedAt).toLocaleDateString()} by the parent/guardian from
          TarragonHealth vaccination records.
        </Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Vaccination status</Text>
          <View style={styles.headerRow}>
            <Text style={styles.col1}>Vaccine</Text>
            <Text style={styles.col2}>Status</Text>
            <Text style={styles.col3}>Last dose</Text>
          </View>
          {data.vaccines.map((v) => (
            <View key={v.name} style={styles.row}>
              <Text style={styles.col1}>{v.name}</Text>
              <Text style={styles.col2}>{VACCINATION_STATUS_LABEL[v.status]}</Text>
              <Text style={styles.col3}>
                {v.lastDoseDate
                  ? `${new Date(v.lastDoseDate).toLocaleDateString()} (dose ${v.dosesGiven})`
                  : "No doses recorded"}
              </Text>
            </View>
          ))}
        </View>

        <Text style={styles.footer}>
          This summary was generated by the child&apos;s parent/guardian from their own
          TarragonHealth account and reflects self-reported and provider-logged records at the
          time it was generated. It intentionally contains vaccination status only — no
          diagnoses, medications, screening results, or other clinical detail. It is not a
          doctor-signed certificate; contact TarragonHealth to request one if your school
          requires a signed attestation.
        </Text>
      </Page>
    </Document>
  );
}
