/**
 * GENERATED by `node scripts/audio/ingest-recordings.mjs`. Do not edit by hand.
 *
 * File name -> Metro asset module id, for every recording in `apps/mobile/assets/audio/` that the manifest lists
 * as bundled. Empty today: no clip has been recorded yet, so every clip shows its text.
 */
export const BUNDLED_AUDIO: Readonly<Record<string, number>> = {};
