import { StateGraph, Annotation, START, END } from "@langchain/langgraph";
import { ChatAnthropic } from "@langchain/anthropic";
import { AIMessage, HumanMessage, SystemMessage, ToolMessage } from "@langchain/core/messages";
import { z } from "zod";
import type { SupabaseClient } from "@supabase/supabase-js";
import {
  COACH_TIERS,
  COACH_SUGGESTED_ACTIONS,
  type CoachChatMessage,
  type CoachSource,
  type CoachTier,
  type CoachSuggestedAction,
  type Database,
  SELF_HARM_REPLY,
} from "@tarragon/shared";
import {
  COACH_SYSTEM_PROMPT,
  COACH_UNAVAILABLE_REPLY,
  DISCLAIMER_LINE,
  EMERGENCY_SAFETY_REPLY,
  SYMPTOM_SUGGESTION_INTRO,
} from "./prompts";
import { detectEmergencyKeywords, isSelfHarmMessage } from "./keyword-guardrail";
import { decideClarification } from "./clarify";
import { emergencyAddendumFor } from "./nearest-hospital";
import { pageOnCallForSelfHarm } from "./emergency-page";
import { loadAssistantMemory, memoryContextLine } from "./memory";
import {
  DOSE_REFUSAL_REPLY,
  SENSITIVE_RESULT_REPLY,
  classifyDoseRequest,
  screenDoseAdvice,
  screenSensitiveResultQuestion,
  screenSensitiveResultReply,
} from "./reply-screen";
import { describesNewSymptoms } from "./symptom-handoff";
import { looksLikeHealthInformationQuestion } from "./info-question";
import { loadKnowledgeSources, toCoachSource } from "./knowledge-sources";
import { evidenceFromTool } from "./tool-evidence";
import { matchSymptomClustersFromText } from "@/lib/symptom-check/symptom-clusters";
import { loadPatientContext } from "./context";
import { logAiCoachEscalation, logAiCoachReviewFlag } from "./escalate";
import { buildAnthropicModel, getConfiguredModelId } from "./model";
import { buildPatientRecordTools } from "./tools";
import { buildReferralRequestTool } from "./referral-tool";
import { findRelevantLifestyleContent } from "@/lib/lifestyle/find-relevant-content";
import { findRelevantHealthEducationContent } from "./knowledge-base";

const structuredReplySchema = z.object({
  tier: z.enum(COACH_TIERS),
  reply: z.string(),
  // §78.2 -- classification only, never executed by the model itself. See
  // COACH_SUGGESTED_ACTIONS' doc comment for the full contract.
  suggestedAction: z.enum(COACH_SUGGESTED_ACTIONS),
  // S51 (7.2): true when the patient is asking for health or medical INFORMATION (what something is, what it means, whether something is
  // safe), as opposed to logging, motivation, scheduling or a question about their own record. The graph uses it to refuse, in code,
  // to answer such a question when nothing reviewed was retrieved. The model only classifies; it cannot override the refusal.
  isHealthInformationRequest: z.boolean(),
});

/** Fixed reply when a health-information question has no reviewed source behind it (S51, 7.2). Never generated by the model. */
export const NO_REVIEWED_SOURCE_REPLY =
  "I don't have reviewed information from your care team on that yet, so I would rather not guess. Please send your care team a message in the app and they will answer it properly.";

/** Hard cap on tool-calling round trips within a single turn — see llmTurn's
 * tool loop below. Bounds latency/cost and guarantees the loop always
 * terminates and reaches the final structured classify+reply call, even if
 * the model kept requesting more tools. */
const MAX_TOOL_ITERATIONS = 4;

const CoachState = Annotation.Root({
  profileId: Annotation<string>,
  organisationId: Annotation<string>,
  conversationId: Annotation<string>,
  incomingMessage: Annotation<string>,
  priorMessages: Annotation<CoachChatMessage[]>,
  tier: Annotation<CoachTier | null>({ reducer: (_prev, next) => next, default: () => null }),
  reply: Annotation<string>({ reducer: (_prev, next) => next, default: () => "" }),
  /** S52 (INV-05): the emergency message was self-harm wording. Gets its own copy and an on-call page. */
  selfHarm: Annotation<boolean>({ reducer: (_prev, next) => next, default: () => false }),
  /** §78.2 in-chat suggestion the model classified for this reply -- see
   * COACH_SUGGESTED_ACTIONS' doc comment for the full contract. */
  suggestedAction: Annotation<CoachSuggestedAction>({ reducer: (_prev, next) => next, default: () => "none" }),
  /** The model id actually used for this turn's classify+reply call — null
   * if the turn never reached a model call (keyword-guardrail-only). Feeds
   * ai_assistant_turns.model_id (audit.ts), via index.ts. Also an honest
   * "no model was used" signal for §78.18 auditability. */
  modelId: Annotation<string | null>({ reducer: (_prev, next) => next, default: () => null }),
  /** Approved-content ids (lpe_content_blocks + health_education_content)
   * the retrieval stage actually surfaced for this turn — feeds
   * ai_assistant_turns.retrieved_source_ids. */
  retrievedSourceIds: Annotation<string[]>({ reducer: (_prev, next) => next, default: () => [] }),
  /** §78.18 "knowledge source" auditability -- human-readable titles (not
   * ids) of any retrieved content that fed this reply, carried through to
   * the persisted message (index.ts) and the audit_log event for a
   * clinician_review flag. Deliberately separate from retrievedSourceIds
   * above (that's the audit-row-level id linkage; this is what the patient-
   * facing message and audit_log event actually display). */
  knowledgeSourceUsed: Annotation<string[]>({ reducer: (_prev, next) => next, default: () => [] }),
  /** S51 (7.2, 7.9): the structured sources behind the reply, shown to the patient. Built from rows the code read, never model-supplied. */
  sources: Annotation<CoachSource[]>({ reducer: (_prev, next) => next, default: () => [] }),
  /** Names of the read-only record tools (tools.ts) the model actually
   * called this turn, for the audit row's input_snapshot — not the same
   * thing as retrievedSourceIds (approved *content*, not record lookups). */
  toolsCalled: Annotation<string[]>({ reducer: (_prev, next) => next, default: () => [] }),
  /** True only when llmTurn's own try/catch caught a model failure and
   * degraded to COACH_UNAVAILABLE_REPLY — distinct from a clean
   * 'clinician_review' classification, which is not a degraded turn. */
  degraded: Annotation<boolean>({ reducer: (_prev, next) => next, default: () => false }),
  errorMessage: Annotation<string | null>({ reducer: (_prev, next) => next, default: () => null }),
  /** Set only when this turn actually caused one to exist (escalate()
   * node). clinicianAlertId is set on both the emergency and
   * clinician_review paths; escalationId (the real `escalations` row, not
   * the alert) only on the emergency path — logAiCoachReviewFlag never
   * creates one, matching its own "clinician_review isn't an escalation"
   * design note. */
  clinicianAlertId: Annotation<string | null>({ reducer: (_prev, next) => next, default: () => null }),
  escalationId: Annotation<string | null>({ reducer: (_prev, next) => next, default: () => null }),
  /** §36.14 human handoff — the care_messages thread opened for the patient
   * to see the clinician's reply in-app. Only ever set on the emergency
   * path (see escalate.ts's logAiCoachEscalation) — clinician_review has no
   * real `escalations` row to link a thread to via
   * care_message_threads.escalation_id, so that path is left unlinked for
   * now (docs/AI_HEALTH_ASSISTANT_ARCHITECTURE.md §7 Phase D). */
  careMessageThreadId: Annotation<string | null>({ reducer: (_prev, next) => next, default: () => null }),
  /** §36.10 referral-request path (referral-tool.ts) — set when the model
   * actually called requestSpecialistReferral this turn. Deliberately
   * separate from clinicianAlertId/escalationId above (those are the
   * keyword-guardrail/llmTurn emergency-classification outcome; this is a
   * tool call that can happen on ANY tier, including 'routine'). */
  referralRequestClinicianAlertId: Annotation<string | null>({ reducer: (_prev, next) => next, default: () => null }),
  referralRequestCareMessageThreadId: Annotation<string | null>({
    reducer: (_prev, next) => next,
    default: () => null,
  }),
  /** Exactly what was sent to the model for this turn — context lines,
   * retrieved source ids, tools called, prior-message window size. Feeds
   * ai_assistant_turns.input_snapshot (audit.ts), via index.ts. Never the
   * raw patient message body (that already lives in
   * ai_conversations.messages). */
  inputSnapshotForAudit: Annotation<Record<string, unknown>>({ reducer: (_prev, next) => next, default: () => ({}) }),
});

export type CoachGraphState = typeof CoachState.State;

export interface CoachGraphDeps {
  /** Patient's own RLS-scoped session — reads/writes ai_conversations and audit_log. */
  supabase: SupabaseClient<Database>;
  /** Staff-write-only tables (clinician_alerts, escalations) the patient's own session
   * can't insert into. Lazy — only constructed if an emergency actually needs escalating,
   * so a missing SUPABASE_SERVICE_ROLE_KEY doesn't break the routine/clinician_review paths. */
  getServiceRoleSupabase: () => SupabaseClient<Database>;
  /** Injectable for tests; defaults to a real Claude client. */
  model?: ChatAnthropic;
  /**
   * The governed system prompt for AI-001, when a Clinical Director has
   * activated one (Module 40.6). Undefined means no governed version is
   * active, and the in-repo COACH_SYSTEM_PROMPT constant is used — which is
   * the normal state, and must stay a working state: a governance table that
   * could take the coach down by being empty would make governance itself
   * the single point of failure 40.18 exists to prevent.
   */
  systemPrompt?: string;
}

/**
 * Appends a fixed, clinician-authored test suggestion to an already-decided
 * non-emergency reply, if `incomingMessage` matches one of the curated
 * clusters in lib/symptom-check/symptom-clusters.ts. The LLM never decides
 * this — a deterministic regex match against clinician-authored data does,
 * same principle as EMERGENCY_SAFETY_REPLY being appended rather than
 * generated. Callers must only invoke this once a message is already
 * confirmed non-emergency (both by keywordGuardrail and by the LLM's own
 * tier), since this function does no emergency classification of its own.
 */
export function appendSymptomSuggestion(reply: string, incomingMessage: string): string {
  const clusters = matchSymptomClustersFromText(incomingMessage);
  if (clusters.length === 0) return reply;
  const suggestions = clusters
    .map(
      (cluster) =>
        `${cluster.name}: ${cluster.patientExplanation} You can request this test in the app, or book a doctor's consultation first if you'd rather talk it through before testing.`
    )
    .join("\n\n");
  return `${reply}\n\n${SYMPTOM_SUGGESTION_INTRO}\n\n${suggestions}`;
}

export type ModelReplyResult = z.infer<typeof structuredReplySchema>;

export interface FinalizedReply {
  tier: CoachTier;
  reply: string;
  suggestedAction: CoachSuggestedAction;
  sources: CoachSource[];
  /** Which deterministic screen replaced the model's text, when one did. Goes to the audit snapshot. */
  replacedBy?: "inv04_sensitive_result_screen" | "dose_advice_screen" | "no_reviewed_source";
}

/**
 * Everything that happens to the model's structured answer before a patient sees it. Pure and deterministic, so each rule is unit
 * tested without a model. Order matters: an emergency is never softened by a later rule, and a safety screen runs before the
 * grounding rule.
 *
 *  1. emergency tier: the model's text plus the fixed emergency copy, no suggestion chip.
 *  2. INV-04: a reply that names a sensitive screening result is replaced and routed to the care team.
 *  3. spec 7.4: a reply that proposes a dose, an increase, a stop or a double is replaced and routed to the care team.
 *  4. spec 7.2: a health-information question with nothing reviewed behind it is refused in code (never answered from general knowledge).
 *  5. spec 7.6: a plain description of new symptoms always carries the symptom-check hand-off, even if the model said "none".
 */
export function finalizeModelReply(input: {
  result: ModelReplyResult;
  incomingMessage: string;
  /** Anything was read (the patient's record, protocol limits, reviewed content). Decides whether sources are shown. */
  grounded: boolean;
  /**
   * Reviewed content or an already-shown explanation backs the answer. Only this lets a health-information question be answered: a
   * record lookup tells the model what the patient's numbers ARE, not what they MEAN, so it cannot ground an explanation.
   */
  reviewGrounded?: boolean;
  sources: CoachSource[];
}): FinalizedReply {
  const { result, incomingMessage, grounded, sources } = input;
  const reviewGrounded = input.reviewGrounded ?? grounded;
  const handOff: CoachSuggestedAction =
    result.suggestedAction === "none" && describesNewSymptoms(incomingMessage) ? "symptom_check" : result.suggestedAction;
  if (result.tier === "emergency") {
    return { tier: "emergency", reply: `${result.reply}\n\n${EMERGENCY_SAFETY_REPLY}`, suggestedAction: "none", sources: [] };
  }
  if (screenSensitiveResultReply(result.reply)) {
    return { tier: "clinician_review", reply: SENSITIVE_RESULT_REPLY, suggestedAction: "none", sources: [], replacedBy: "inv04_sensitive_result_screen" };
  }
  if (screenDoseAdvice(result.reply)) {
    return { tier: "clinician_review", reply: DOSE_REFUSAL_REPLY, suggestedAction: "none", sources: [], replacedBy: "dose_advice_screen" };
  }
  // The model's own flag OR the deterministic floor: the refusal never depends on the model saying the question is informational.
  if ((result.isHealthInformationRequest || looksLikeHealthInformationQuestion(incomingMessage)) && !reviewGrounded) {
    return {
      tier: result.tier,
      reply: NO_REVIEWED_SOURCE_REPLY,
      // new symptoms still go to the symptom check: the refusal must not drop the 7.6 hand-off
      suggestedAction: handOff === "symptom_check" ? "symptom_check" : "none",
      sources: [],
      replacedBy: "no_reviewed_source",
    };
  }
  return {
    tier: result.tier,
    reply: appendSymptomSuggestion(`${result.reply}\n\n${DISCLAIMER_LINE}`, incomingMessage),
    suggestedAction: handOff,
    sources: grounded ? sources : [],
  };
}

/** Builds the AI Coach's LangGraph turn:
 *
 *   START -> keywordGuardrail -+-> (emergency) -> escalate -> END
 *                               \-> llmTurn -+-> (emergency) -> escalate -> END
 *                                             +-> (clinician_review) -> logReview -> END
 *                                             +-> (routine) -> END
 *
 * `keywordGuardrail` is a deterministic regex pass that never calls Claude —
 * a safety net that still works if the model is unreachable. `llmTurn` only
 * runs when the keyword pass didn't already flag an emergency, and itself
 * degrades to the cautious 'clinician_review' tier (never silently
 * 'routine') on any Claude failure.
 *
 * `llmTurn` itself has two phases: a bounded tool-calling loop (tools.ts's
 * read-only record tools — vitals, medications, allergies, appointments,
 * conditions, recent labs) so the model can ground an answer in the
 * patient's own record instead of guessing, followed by one final
 * structured call that classifies the tier and produces the reply. The
 * tools are strictly read-only (see tools.ts's own HARD INVARIANT comment)
 * — tool-calling only ever adds grounding before the same classify step
 * that already existed, never a way to bypass it or take an action.
 *
 * The graph only decides what to say and whether to escalate — it does not
 * write to ai_conversations itself. Persisting the turn happens once in
 * runCoachTurn() (index.ts), against the full, untruncated message history;
 * `state.priorMessages` here is deliberately windowed (see HISTORY_LIMIT in
 * index.ts) for LLM context only, so building persistence on top of it would
 * silently drop everything older than the window on every turn.
 */
export function buildCoachGraph(deps: CoachGraphDeps) {
  function keywordGuardrail(state: CoachGraphState) {
    if (detectEmergencyKeywords(state.incomingMessage)) {
      return { tier: "emergency" as const, reply: EMERGENCY_SAFETY_REPLY };
    }
    // INV-04: a question about an HIV / hepatitis B / hepatitis C result is never answered by the assistant, and the
    // model is never reached. Fixed copy routes to the care team, and the care team is flagged (clinician_review).
    if (screenSensitiveResultQuestion(state.incomingMessage)) {
      return { tier: "clinician_review" as const, reply: SENSITIVE_RESULT_REPLY, suggestedAction: "none" as const };
    }
    // S51 (7.4): a request to change, skip, stop or double a medicine is refused in code and routed to the care team. No model call.
    // A change (stop, skip, double, increase) also flags the care team; a plain "how much should I take" gets the same reply without a flag.
    const doseRequest = classifyDoseRequest(state.incomingMessage);
    if (doseRequest !== "none") {
      return {
        tier: doseRequest === "change" ? ("clinician_review" as const) : ("routine" as const),
        reply: DOSE_REFUSAL_REPLY,
        suggestedAction: "none" as const,
      };
    }
    return {};
  }

  // S52 (7.11): a short question before answering a message too unclear to answer safely. Runs only after every safety screen above,
  // so an emergency, a dose request or a sensitive-result question is never held up by it. No model call.
  function clarify(state: CoachGraphState) {
    const c = decideClarification({ message: state.incomingMessage, priorMessages: state.priorMessages });
    if (!c) return {};
    return {
      tier: "routine" as const,
      reply: c.reply,
      suggestedAction: "none" as const,
      inputSnapshotForAudit: { clarification: c.topic },
    };
  }

  // S52 (7.8, INV-06): the emergency reply is the fixed copy, plus the nearest hospitals and the patient's own emergency contact read
  // from data we hold (best effort, bounded; the fixed copy always stands alone). Self-harm wording gets its own copy.
  async function emergencyContext(state: CoachGraphState) {
    const selfHarm = isSelfHarmMessage(state.incomingMessage);
    const base = selfHarm ? SELF_HARM_REPLY : state.reply;
    const addendum = await emergencyAddendumFor(deps.supabase, state.profileId);
    return { selfHarm, reply: addendum ? `${base}\n\n${addendum}` : base };
  }

  async function llmTurn(state: CoachGraphState) {
    const context = await loadPatientContext(deps.supabase, state.profileId);
    const contextLines: string[] = [];

    // Deliberately narrow static context — demographics + risk tiers +
    // lifestyle programme state only. Everything else loadPatientContext
    // now also reads (medications, allergies, vitals, labs, appointments,
    // conditions — docs/AI_HEALTH_ASSISTANT_ARCHITECTURE.md §4.2) is
    // available on demand via the read-only tools below instead of being
    // pushed into every single prompt regardless of relevance — see the
    // architecture doc's §4.1 comparison of "wide static context" against
    // "retrieval tools" and its PHI-minimisation reasoning for preferring
    // tools. loadPatientContext's fuller snapshot is also what the Phase C
    // composed surfaces (explain-record, this-month, appointment-prep)
    // read directly, deterministically, with no LLM involved.
    if (context.demographics.ageYears !== null || context.demographics.sex) {
      const parts = [
        context.demographics.ageYears !== null ? `${context.demographics.ageYears} years old` : null,
        context.demographics.sex,
      ].filter(Boolean);
      if (parts.length > 0) contextLines.push(`The patient is ${parts.join(", ")}.`);
    }
    if (context.elevatedConditions.length > 0) {
      contextLines.push(
        `The patient currently has an elevated risk tier for: ${context.elevatedConditions.join(", ")}.`
      );
    }
    // §78.17 safety-layer signals — bias towards caution, never towards false
    // reassurance. These only ever push the classification towards
    // clinician_review; the tier-classification instructions in the system
    // prompt remain the real enforcement, this just gives the model the
    // fact it needs to apply "when in doubt, pick the more cautious tier"
    // correctly for these specific situations.
    if (context.highRiskConditions.length > 0) {
      contextLines.push(
        `The patient has a HIGH or VERY HIGH risk tier (not just elevated) for: ` +
          `${context.highRiskConditions.join(", ")}. Be more readily cautious about any symptom-adjacent ` +
          `message from this patient -- prefer clinician_review over routine when genuinely unsure.`
      );
    }
    if (context.isPregnant) {
      contextLines.push(
        `The patient is currently pregnant. Any symptom, medication question, or bleeding/pain report ` +
          `should be treated more cautiously than for a non-pregnant patient -- prefer clinician_review ` +
          `over routine when genuinely unsure, and never suggest an over-the-counter medication.`
      );
    }
    if (context.possibleMinor) {
      contextLines.push(
        `This account's date of birth on file suggests the patient may be under 18. This platform is ` +
          `built for adult self-enrolment, so treat this as an edge case worth extra caution rather than ` +
          `a supported scenario -- prefer clinician_review over routine when genuinely unsure, and avoid ` +
          `any guidance that assumes an adult's judgement or independence.`
      );
    }
    // Per-programme grounding. A paused/flagged programme gets a deference
    // instruction instead of goal talk — mirrors, at the prompt level, the
    // same hard rule @tarragon/lifestyle-engine's applyGuardrails() enforces
    // in code (never push weight-loss/programme content at a paused or
    // flagged enrolment). The deterministic keyword guardrail and the
    // tier-classification instructions above remain the real enforcement
    // backstops regardless of what's injected here.
    for (const p of context.lifestyleProgrammes) {
      if (p.status === "paused" || p.hasOpenRedFlag) {
        contextLines.push(
          `The patient's ${p.conditionLabel} lifestyle programme is currently paused or flagged ` +
            `for a doctor's review. Do not encourage progress toward its goals or suggest pushing ` +
            `forward — acknowledge it supportively and point them to their care team if they bring it up.`
        );
      } else {
        const goalsPart =
          p.goalTitles.length > 0 ? ` Current goals: ${p.goalTitles.join(", ")}.` : "";
        contextLines.push(
          `The patient is enrolled in a ${p.conditionLabel} lifestyle programme` +
            (p.currentPhaseName ? `, currently in the "${p.currentPhaseName}" phase.` : ".") +
            goalsPart
        );
      }
    }

    // Multi-source retrieval — closes the "one library out of three" gap
    // (docs/AI_HEALTH_ASSISTANT_ARCHITECTURE.md §2.4/§7 Phase B).
    //
    // This block used to be wrapped in `if (embedder)`, and the comment here
    // used to claim it would "start surfacing content automatically the
    // moment either is populated". It never did. The only Embedder is Voyage,
    // VOYAGE_API_KEY has never been set on this platform, so `embedder` was
    // always null, retrieval was skipped whole, and every coach reply in
    // production was ungrounded — with `retrievedSourceIds: []` on the audit
    // row making it look like an honest "nothing relevant found". Both
    // finders now take a nullable embedder and fall back to keyword search
    // over the same clinician-reviewed rows, so retrieval runs on every turn
    // and only the ranking quality depends on the vendor.
    const retrievedSourceIds: string[] = [];
    // §78.18 "knowledge source" auditability -- human-readable titles (as
    // opposed to retrievedSourceIds' ids) of any retrieved content that fed
    // this reply, carried through to the persisted message and the
    // audit_log event regardless of which branch below returns.
    const knowledgeSourceUsed: string[] = [];
    // AI-009's own registered excluded_population is explicit: "Any
    // patient-authored text. Patient content is never sent to the embedding
    // provider." Both retrieval calls below query on `state.incomingMessage`
    // -- the patient's own chat text -- so a real Voyage embedder must NEVER
    // be passed here, or embed() sends that text straight to Voyage. This
    // was previously masked entirely: VOYAGE_API_KEY has never been set on
    // this platform, so `embedder` here was always null anyway and this
    // never actually happened -- but the code as written would have sent
    // every patient message to Voyage the moment a real key was configured
    // anywhere the app reads it from (found and fixed during the AI-009
    // evaluation, 2026-09-17, the same session that finally got a real key
    // configured to test with). Deliberately `null`, not `deps.embedder`:
    // this call site must always use the lexical fallback
    // (findRelevantLifestyleContent/findRelevantHealthEducationContent both
    // already fall back gracefully to keyword search over the same
    // clinician-reviewed rows on a null embedder, so retrieval quality is
    // unaffected here -- only ranking method). The real Voyage embedder is
    // still used correctly elsewhere (e.g. coaching-proposer.ts's nudge
    // retrieval), where the query text is clinician-authored programme
    // metadata, never the patient's own words.
    const embedder = null;
    // 1. Lifestyle content — deliberately still scoped to the patient's
    // own active (non-paused, non-flagged) lifestyle programme, by
    // design (see find-relevant-content.ts's own docstring). A
    // paused/flagged programme already got a deference instruction
    // above and shouldn't also be handed goal-adjacent reading material.
    const activeProgramme = context.lifestyleProgrammes.find(
      (p) => p.status !== "paused" && !p.hasOpenRedFlag
    );
    // S52 (7.12): the patient's own remembered goals and preferences, only with their consent and only while AI-020 is on.
    const memoryLines = await loadAssistantMemory(deps.supabase);
    const memoryContext = memoryContextLine(memoryLines);
    if (memoryContext) contextLines.push(memoryContext);

    const lifestyleCandidates = activeProgramme
      ? await findRelevantLifestyleContent(deps.supabase, embedder, state.incomingMessage, {
          matchCount: 2,
          conditionFilter: activeProgramme.condition,
        })
      : [];

    // 2. General health-education content — NOT scoped to lifestyle
    // enrolment (unlike the source above), so a patient with no
    // programme at all still gets grounded, reviewed reference material
    // for a general question. This is the source that was previously
    // not retrievable at all — see the architecture doc §2.4/§4.
    const educationCandidates = await findRelevantHealthEducationContent(deps.supabase, embedder, state.incomingMessage, {
      matchCount: 2,
    });

    // S51 (7.2): only rows with an owner clinician, a version and a review date that has not passed are used. The check is a database
    // read (assistant_knowledge_sources) and fails closed: if it fails, nothing counts as reviewed and nothing is cited.
    const knowledgeMeta = await loadKnowledgeSources(deps.supabase, [
      ...lifestyleCandidates.map((r) => r.id),
      ...educationCandidates.map((r) => r.id),
    ]);
    const relevant = lifestyleCandidates.filter((r) => knowledgeMeta.get(r.id)?.retrievable === true);
    const relevantEducation = educationCandidates.filter((r) => knowledgeMeta.get(r.id)?.retrievable === true);
    const sources: CoachSource[] = [];
    for (const r of [...relevant, ...relevantEducation]) {
      const k = knowledgeMeta.get(r.id);
      if (k) sources.push(toCoachSource(k));
    }

    if (relevant.length > 0) {
      retrievedSourceIds.push(...relevant.map((r) => r.id));
      knowledgeSourceUsed.push(...relevant.map((r) => r.title));
      contextLines.push(
        "Clinician-approved reference material that may be relevant to this message " +
          "(use it to inform your answer in your own words and voice, don't quote it at " +
          "length or present it as a document):\n" +
          relevant.map((r) => `- ${r.title}: ${r.bodyMd}`).join("\n")
      );
    }
    if (relevantEducation.length > 0) {
      retrievedSourceIds.push(...relevantEducation.map((r) => r.id));
      knowledgeSourceUsed.push(...relevantEducation.map((r) => r.title));
      contextLines.push(
        "Clinician-approved health education material that may be relevant to this message " +
          "(use it to inform your answer in your own words and voice, don't quote it at length " +
          "or present it as a document):\n" +
          relevantEducation.map((r) => `- ${r.title}: ${r.excerpt}`).join("\n")
      );
    }

    const contextLine = contextLines.join("\n\n");
    // deps.systemPrompt is the governed prompt override (Module 40.6) — set
    // only when a Clinical Director has activated an approved version for
    // AI-001 in the AI governance console. Falls back to the in-repo
    // COACH_SYSTEM_PROMPT constant, which must stay a working default: a
    // governance table that could take the coach down by being empty would
    // make governance itself the single point of failure 40.18 exists to
    // prevent.
    const basePrompt = deps.systemPrompt ?? COACH_SYSTEM_PROMPT;
    const systemPrompt = contextLine ? `${basePrompt}\n\n${contextLine}` : basePrompt;

    const history = state.priorMessages.map((message) =>
      message.role === "user" ? new HumanMessage(message.content) : new AIMessage(message.content)
    );

    const modelId = getConfiguredModelId();
    const toolsCalled: string[] = [];
    let toolGrounded = false;
    let referralRequestClinicianAlertId: string | null = null;
    let referralRequestCareMessageThreadId: string | null = null;

    try {
      // Built inside the try block, not at graph-build time — a missing/invalid
      // ANTHROPIC_API_KEY must degrade this turn, not throw before we can catch it.
      const model = deps.model ?? buildAnthropicModel({ maxTokens: 500 });

      // Phase 1: bounded tool-calling loop. Offers the model read-only
      // record lookups so it can ground an answer in the patient's own
      // vitals/medications/allergies/appointments/conditions/labs instead
      // of guessing (docs/AI_HEALTH_ASSISTANT_ARCHITECTURE.md §4.1), plus
      // the one write-capable tool (referral-tool.ts — see its own header
      // for why it's built this way). Most turns (general questions,
      // chit-chat) won't trigger a tool call at all — the loop exits after
      // the first response with none.
      const tools = [
        ...buildPatientRecordTools(deps.supabase, state.profileId),
        buildReferralRequestTool({
          patientSupabase: deps.supabase,
          getServiceRoleSupabase: deps.getServiceRoleSupabase,
          organisationId: state.organisationId,
          patientId: state.profileId,
          conversationId: state.conversationId,
          onReferralRequested: (result) => {
            referralRequestClinicianAlertId = result.clinicianAlertId;
            referralRequestCareMessageThreadId = result.careMessageThreadId;
          },
        }),
      ];
      const toolsByName = new Map(tools.map((t) => [t.name, t]));
      const modelWithTools = model.bindTools(tools);

      // cache_control on the newest turn (not the system message) is the
      // "multi-turn conversation" caching pattern: it marks system + all prior
      // history + this message as one cached prefix, so next turn's request
      // re-reads everything up to here instead of re-billing it, and only
      // pays full price for whatever's new. The system message + a single
      // turn or two often sits under Sonnet 5's 1024-token cacheable-prefix
      // minimum (a marker below it is a documented no-op, not an error), so
      // this mostly starts paying off from the 3rd exchange in a session
      // onward — but it costs nothing on the turns where it doesn't.
      const messages: (SystemMessage | HumanMessage | AIMessage | ToolMessage)[] = [
        new SystemMessage(systemPrompt),
        ...history,
        new HumanMessage({
          content: [
            { type: "text", text: state.incomingMessage, cache_control: { type: "ephemeral" } },
          ],
        }),
      ];

      for (let iteration = 0; iteration < MAX_TOOL_ITERATIONS; iteration++) {
        const response = await modelWithTools.invoke(messages);
        // Only pushed when it actually carries a tool call. A response with
        // none ends the loop, and pushing it anyway would leave `messages`
        // ending in an assistant turn going into the structuredModel call
        // below — claude-sonnet-5 and the rest of the 4.6+ family reject
        // that as unsupported assistant-message prefill ("the conversation
        // must end with a user message"), which silently degraded every
        // turn that used at least one tool call before settling on its
        // final answer to clinician_review. The draft text in a dropped
        // response was never shown to the patient anyway — Phase 2 always
        // regenerates the real reply from the tool-result history.
        if (!response.tool_calls || response.tool_calls.length === 0) break;
        messages.push(response);

        for (const call of response.tool_calls) {
          const matchedTool = toolsByName.get(call.name);
          const output = matchedTool
            ? await matchedTool.invoke(call.args)
            : JSON.stringify({ error: `Unknown tool: ${call.name}` });
          toolsCalled.push(call.name);
          const evidence = evidenceFromTool(call.name, output);
          if (evidence.grounded) {
            toolGrounded = true;
            if (evidence.source && !sources.some((x) => x.kind === evidence.source!.kind && x.title === evidence.source!.title)) {
              sources.push(evidence.source);
            }
          }
          messages.push(new ToolMessage({ content: output, tool_call_id: call.id ?? call.name, name: call.name }));
        }
      }

      // Phase 2: final classify+reply call, over the same message history
      // (including whatever tool exchanges just happened) — tool-calling
      // only ever adds grounding ahead of this step, never replaces or
      // bypasses it. A separate structured-output-bound model instance,
      // not modelWithTools, since withStructuredOutput and bindTools
      // configure the request differently.
      const structuredModel = model.withStructuredOutput(structuredReplySchema);
      const result = await structuredModel.invoke(messages);

      const inputSnapshot = {
        memoryItemCount: memoryLines.length,
        contextLines,
        retrievedSourceIds,
        toolsCalled,
        historyMessageCount: history.length,
        referralRequestClinicianAlertId,
        referralRequestCareMessageThreadId,
      };

      const final = finalizeModelReply({
        result,
        incomingMessage: state.incomingMessage,
        grounded: toolGrounded || retrievedSourceIds.length > 0,
        reviewGrounded: sources.some((x) => x.kind === "reviewed_content" || x.kind === "explanation"),
        sources,
      });
      return {
        tier: final.tier,
        reply: final.reply,
        suggestedAction: final.suggestedAction,
        modelId,
        retrievedSourceIds,
        knowledgeSourceUsed: final.replacedBy ? [] : knowledgeSourceUsed,
        sources: final.sources,
        toolsCalled,
        referralRequestClinicianAlertId,
        referralRequestCareMessageThreadId,
        inputSnapshotForAudit: final.replacedBy ? { ...inputSnapshot, replyReplacedBy: final.replacedBy } : inputSnapshot,
      };
    } catch (error) {
      // Degrading to the patient is correct either way, but swallowing the
      // real cause entirely makes a bad key/model/network issue undebuggable.
      // referralRequestClinicianAlertId/ThreadId are still included here —
      // the referral request write already happened for real (it's a
      // separate try/catch inside the tool itself, see referral-tool.ts) even
      // if something later in this turn subsequently failed.
      console.error("ai-coach: llmTurn failed, degrading to clinician_review", error);
      return {
        tier: "clinician_review" as const,
        reply: COACH_UNAVAILABLE_REPLY,
        modelId,
        retrievedSourceIds,
        toolsCalled,
        referralRequestClinicianAlertId,
        referralRequestCareMessageThreadId,
        degraded: true,
        errorMessage: error instanceof Error ? error.message : String(error),
      };
    }
  }

  async function escalate(state: CoachGraphState) {
    const { clinicianAlertId, escalationId, careMessageThreadId } = await logAiCoachEscalation(
      deps.supabase,
      deps.getServiceRoleSupabase(),
      {
        organisationId: state.organisationId,
        patientId: state.profileId,
        conversationId: state.conversationId,
        triggerMessage: state.incomingMessage,
        recentMessages: state.priorMessages,
        aiAction: state.modelId
          ? "Classified as an emergency by the AI Coach and escalated"
          : "Escalated immediately via deterministic safety-keyword match, before any AI response",
      }
    );
    // INV-05: a self-harm message also pages the on-call clinician now. In addition to the escalation above, never instead of it.
    if (state.selfHarm) await pageOnCallForSelfHarm(deps.getServiceRoleSupabase(), state.profileId, state.conversationId);
    return { clinicianAlertId, escalationId, careMessageThreadId };
  }

  async function logReview(state: CoachGraphState) {
    // Previously audit_log only — correct for the record, but nobody's
    // dashboard reads audit_log, so a real concern could sit unseen
    // indefinitely (see logAiCoachReviewFlag's docstring). Now also opens a
    // real clinician_alerts row so a flagged-but-non-emergency turn actually
    // reaches a worklist, not just a log.
    const { clinicianAlertId } = await logAiCoachReviewFlag(deps.getServiceRoleSupabase(), {
      organisationId: state.organisationId,
      patientId: state.profileId,
      conversationId: state.conversationId,
      triggerMessage: state.incomingMessage,
      recentMessages: state.priorMessages,
      aiAction: "Classified as worth a clinician's review, not urgent",
    });
    await deps.supabase.from("audit_log").insert({
      organisation_id: state.organisationId,
      actor_id: state.profileId,
      action: "ai_coach.clinician_review_flagged",
      entity_type: "ai_conversations",
      entity_id: state.conversationId,
      event: { message: state.incomingMessage, model: state.modelId, knowledge_source: state.knowledgeSourceUsed },
    });
    return { clinicianAlertId };
  }

  return new StateGraph(CoachState)
    .addNode("keywordGuardrail", keywordGuardrail)
    .addNode("clarify", clarify)
    .addNode("llmTurn", llmTurn)
    .addNode("emergencyContext", emergencyContext)
    .addNode("escalate", escalate)
    .addNode("logReview", logReview)
    .addEdge(START, "keywordGuardrail")
    .addConditionalEdges(
      "keywordGuardrail",
      (state) => {
        if (state.tier === "emergency") return "emergencyContext";
        // A deterministic refusal (INV-04, dose) already has its reply: no model call. It flags the care team (clinician_review) or just ends (routine).
        if (state.tier === "clinician_review" && state.reply) return "logReview";
        if (state.reply) return "end";
        return "clarify";
      },
      { emergencyContext: "emergencyContext", clarify: "clarify", logReview: "logReview", end: END }
    )
    .addConditionalEdges("clarify", (state) => (state.reply ? "end" : "llmTurn"), { llmTurn: "llmTurn", end: END })
    .addConditionalEdges(
      "llmTurn",
      (state) => {
        if (state.tier === "emergency") return "emergencyContext";
        if (state.tier === "clinician_review") return "logReview";
        return END;
      },
      { emergencyContext: "emergencyContext", logReview: "logReview", [END]: END }
    )
    .addEdge("emergencyContext", "escalate")
    .addEdge("escalate", END)
    .addEdge("logReview", END)
    .compile();
}
