import "server-only";
import { readFileSync } from "node:fs";
import path from "node:path";

/**
 * The brand lockup, loaded off disk for PDF rendering.
 *
 * ⚠️ BOTH BRAND PNGs ARE RGB WITH NO ALPHA CHANNEL — a solid white background,
 * not transparency. That is the single fact that decides this document's
 * masthead. An earlier draft put the Guard Leaf on a full-bleed Tarragon Green
 * band and it rendered as a white rectangle sitting on the green, because there
 * is no alpha to let the green through. The fix is not to key the white out
 * (the checkmark inside the mark is itself near-white, so a colour key eats it,
 * and doctoring a brand asset to suit one document is the wrong move anyway) —
 * it is to give the lockup the light ground it was drawn for. See the masthead
 * in health-passport-document.tsx.
 *
 * The LOCKUP is used rather than the bare mark because it is the real wordmark:
 * "Tarragon" in near-black, "Health" in Tarragon Green, with the tagline set
 * beneath. Hand-setting that in Helvetica, as an earlier draft did, produced a
 * wordmark that was not the brand's.
 *
 * Read as bytes rather than referenced by URL because @react-pdf fetching a URL
 * at render time would make every download depend on the app being able to reach
 * itself over the network — a slow or blocked request would turn a working
 * document into a hung one. Bytes off the filesystem cannot fail that way.
 *
 * Cached for the process lifetime: the files do not change under a running
 * server, and re-reading them on every download is pure waste.
 *
 * A missing file degrades to a typeset wordmark rather than an exception. A logo
 * is not what makes this document trustworthy — the signature is — so losing it
 * must never lose the passport.
 */

function loadBrandPng(filename: string, cache: { value?: Buffer | null }): Buffer | null {
  if (cache.value !== undefined) return cache.value;
  const candidates = [
    // Normal Next.js server runtime: cwd is apps/web.
    `public/brand/${filename}`,
    // Monorepo root, e.g. a script or a test runner started from the top.
    `apps/web/public/brand/${filename}`,
  ];
  for (const relative of candidates) {
    try {
      cache.value = readFileSync(path.join(process.cwd(), relative));
      return cache.value;
    } catch {
      // try the next candidate
    }
  }
  cache.value = null;
  return cache.value;
}

const lockupCache: { value?: Buffer | null } = {};

/**
 * Guard Leaf + "TarragonHealth" + tagline. The masthead asset.
 *
 * Prefers the transparent copy (generated by
 * `apps/web/scripts/make-transparent-brand-assets.py`, artwork untouched, only
 * the opaque paper removed) and falls back to the original. Transparency is what
 * lets the masthead sit on any of the light grounds BRAND_GUIDE.md §4 approves
 * rather than being locked to pure white; the fallback means a checkout without
 * the generated file still renders a correct document on white.
 */
export function guardLeafLockupPng(): Buffer | null {
  return (
    loadBrandPng("guard-leaf-lockup-transparent.png", lockupCache) ??
    loadBrandPng("guard-leaf-lockup.png", lockupFallbackCache)
  );
}

const lockupFallbackCache: { value?: Buffer | null } = {};

/**
 * The brand system as PDF-ready values.
 *
 * Deliberately a separate set of constants from the dashboard's clinical status
 * colours (green/amber/red/blue/grey). Those signal a patient's clinical state;
 * these are the brand. docs/BRAND_GUIDE.md is explicit that conflating the two
 * is a mistake, and a document that reads as "green = you are fine" when the
 * green is just the letterhead would be exactly that mistake.
 */
export const PDF_BRAND = {
  green: "#0E7C52",
  greenDeep: "#0A5D3D",
  greenTint: "#E8F2EC",
  navy: "#12324B",
  navyTint: "#EDF2F6",
  ink: "#1F2933",
  muted: "#5B6B78",
  hairline: "#DCE4EA",
  paper: "#FFFFFF",
  warm: "#B45309",
  alert: "#B42318",
} as const;
