import type { FoodCatalogueItem } from "./food-catalogue";

/** Small fixture catalogue shared across nutrition module tests — a
 * representative slice of the real seeded data (supabase/migrations/
 * ..._nigerian_food_database.sql), not the full 40+ item list. */
export const FIXTURE_CATALOGUE: FoodCatalogueItem[] = [
  {
    id: "1",
    code: "white_rice",
    name: "White rice (cooked)",
    aliases: ["rice"],
    category: "staple",
    costTier: "budget",
    caloriesKcal100g: 130,
    carbsG100g: 28.2,
    proteinG100g: 2.7,
    fatG100g: 0.3,
    fibreG100g: 0.4,
    sodiumMg100g: 1,
    portions: [
      { unit: "serving", grams: 200, isDefault: true },
      { unit: "spoon", grams: 30, isDefault: false },
      { unit: "plate", grams: 250, isDefault: false },
    ],
  },
  {
    id: "2",
    code: "jollof_rice",
    name: "Jollof rice",
    aliases: ["party rice"],
    category: "staple",
    costTier: "mid",
    caloriesKcal100g: 180,
    carbsG100g: 27,
    proteinG100g: 3.5,
    fatG100g: 6,
    fibreG100g: 1.2,
    sodiumMg100g: 320,
    portions: [
      { unit: "serving", grams: 200, isDefault: true },
      { unit: "spoon", grams: 30, isDefault: false },
      { unit: "plate", grams: 250, isDefault: false },
    ],
  },
  {
    id: "3",
    code: "beans_cooked",
    name: "Beans (cooked)",
    aliases: ["ewa", "cowpea"],
    category: "legume",
    costTier: "budget",
    caloriesKcal100g: 130,
    carbsG100g: 22,
    proteinG100g: 8.5,
    fatG100g: 0.7,
    fibreG100g: 6.5,
    sodiumMg100g: 4,
    portions: [
      { unit: "serving", grams: 150, isDefault: true },
      { unit: "spoon", grams: 25, isDefault: false },
    ],
  },
  {
    id: "4",
    code: "moi_moi",
    name: "Moi moi",
    aliases: ["moin moin", "bean pudding"],
    category: "legume",
    costTier: "mid",
    caloriesKcal100g: 175,
    carbsG100g: 14,
    proteinG100g: 9,
    fatG100g: 9,
    fibreG100g: 4.5,
    sodiumMg100g: 250,
    portions: [{ unit: "piece", grams: 120, isDefault: true }],
  },
  {
    id: "5",
    code: "egusi_soup",
    name: "Egusi soup",
    aliases: [],
    category: "soup",
    costTier: "mid",
    caloriesKcal100g: 180,
    carbsG100g: 4,
    proteinG100g: 12,
    fatG100g: 13,
    fibreG100g: 2.5,
    sodiumMg100g: 420,
    portions: [
      { unit: "serving", grams: 300, isDefault: true },
      { unit: "spoon", grams: 20, isDefault: false },
    ],
  },
  {
    id: "6",
    code: "ewedu_soup",
    name: "Ewedu soup",
    aliases: [],
    category: "soup",
    costTier: "budget",
    caloriesKcal100g: 60,
    carbsG100g: 5,
    proteinG100g: 3,
    fatG100g: 3,
    fibreG100g: 2.5,
    sodiumMg100g: 250,
    portions: [{ unit: "serving", grams: 250, isDefault: true }],
  },
  {
    id: "7",
    code: "chicken_grilled",
    name: "Grilled/roasted chicken",
    aliases: ["chicken"],
    category: "protein",
    costTier: "mid",
    caloriesKcal100g: 165,
    carbsG100g: 0,
    proteinG100g: 31,
    fatG100g: 3.6,
    fibreG100g: 0,
    sodiumMg100g: 75,
    portions: [
      { unit: "piece", grams: 90, isDefault: true },
      { unit: "serving", grams: 100, isDefault: false },
    ],
  },
  {
    id: "8",
    code: "fish_dried",
    name: "Dried/stock fish",
    aliases: ["stockfish"],
    category: "protein",
    costTier: "premium",
    caloriesKcal100g: 290,
    carbsG100g: 0,
    proteinG100g: 62,
    fatG100g: 3,
    fibreG100g: 0,
    sodiumMg100g: 1200,
    portions: [{ unit: "piece", grams: 30, isDefault: true }],
  },
  {
    id: "9",
    code: "eggs_boiled",
    name: "Boiled eggs",
    aliases: ["egg", "eggs"],
    category: "protein",
    costTier: "budget",
    caloriesKcal100g: 155,
    carbsG100g: 1.1,
    proteinG100g: 13,
    fatG100g: 11,
    fibreG100g: 0,
    sodiumMg100g: 124,
    portions: [{ unit: "piece", grams: 50, isDefault: true }],
  },
  {
    id: "10",
    code: "garri",
    name: "Garri (dry, soaked)",
    aliases: ["gari"],
    category: "staple",
    costTier: "budget",
    caloriesKcal100g: 357,
    carbsG100g: 86.9,
    proteinG100g: 1.6,
    fatG100g: 0.7,
    fibreG100g: 2,
    sodiumMg100g: 15,
    portions: [{ unit: "serving", grams: 50, isDefault: true }],
  },
];
