import {
  Accessibility,
  AlertCircle,
  Activity,
  Bell,
  Bluetooth,
  Calendar,
  CheckCheck,
  ClipboardList,
  Clock,
  CreditCard,
  Dumbbell,
  FileText,
  FlaskConical,
  Flame,
  Footprints,
  GraduationCap,
  Gauge,
  Heart,
  HandHelping,
  Home,
  Leaf,
  LifeBuoy,
  Lock,
  MessageCircle,
  Moon,
  Pill,
  Receipt,
  Search,
  Settings,
  ShieldCheck,
  Smile,
  Sparkles,
  Trophy,
  User,
  Users,
  Utensils,
  Wallet,
  Wine,
  Wrench,
  type LucideIcon,
} from "lucide-react-native";
import type { SectionId } from "@/lib/sections";

/**
 * One Lucide icon per patient-app section, for the menu drawer. Kept apart from
 * lib/sections.ts (which still carries the old Ionicons names for the screens that
 * have not moved) so the rest of the app is unaffected. Record<SectionId, ...> makes
 * a new section without an icon a type error rather than a blank tile.
 */
export const SECTION_ICONS: Record<SectionId, LucideIcon> = {
  overview: Home,
  myActions: CheckCheck,
  vitals: Activity,
  medications: Pill,
  labs: FlaskConical,
  devices: Bluetooth,
  prevention: ShieldCheck,
  healthSummary: FileText,
  timeline: Clock,
  womensHealth: User,
  sexualHealth: Heart,
  wellbeing: Smile,
  healthCheck: ClipboardList,
  findASpecialist: Search,
  healthyAgeing: Accessibility,
  meals: Utensils,
  sleep: Moon,
  activity: Footprints,
  exercise: Dumbbell,
  smoking: Flame,
  alcohol: Wine,
  lifestyle: Leaf,
  weightManagement: Gauge,
  learn: GraduationCap,
  wellness: Trophy,
  messages: MessageCircle,
  aiCoach: Sparkles,
  appointments: Calendar,
  care: LifeBuoy,
  services: CreditCard,
  family: Users,
  supporting: HandHelping,
  screeningDays: Users,
  passport: FileText,
  financialProfile: Wallet,
  receipts: Receipt,
  notificationSettings: Bell,
  technicalSupport: Wrench,
  privacy: Lock,
  emergency: AlertCircle,
  settings: Settings,
};
