-- Tarragon Health — Legal documentation v2 (2026-07-29)
-- Supersedes the one-paragraph placeholder consent_versions rows seeded by
-- 20260716180000_patient_consent.sql with the full drafted schedules
-- (Schedule A/B/C in docs/legal/) — still a draft pending counsel review
-- (see docs/legal/cover-memo-to-counsel.md), but substantially more complete
-- than the launch placeholder: NDPA 2023 framing, the eu-west-1 cross-border
-- transfer disclosure, the tiered doctor model, the 4-hour abnormal-result
-- SLA, and real subscription/cancellation terms all now appear in the text
-- the platform actually shows and records acceptance against.
--
-- consent_versions is append-only by design (20260716180000's own comment);
-- this migration does not edit the existing 2026-07-v1 rows, it retires them
-- (is_current -> false) and inserts a new is_current version per type. Every
-- prior patient's acceptance record (patient_consents) still points at the
-- exact version they actually agreed to.
--
-- Also opens consent_versions to anon SELECT (current versions only) so the
-- new public /privacy, /telehealth-consent, and /terms marketing pages can
-- render the live text without an authenticated session — same anon-read
-- pattern already used for marketing_resources.

-- ---------------------------------------------------------------------------
-- Retire the placeholder versions.
-- ---------------------------------------------------------------------------

update public.consent_versions
set is_current = false
where consent_type in ('data_processing', 'telehealth', 'terms_of_service')
  and is_current = true;

-- ---------------------------------------------------------------------------
-- Insert the new versions.
-- ---------------------------------------------------------------------------

insert into public.consent_versions (consent_type, version, title, body, is_current)
values
(
  'data_processing',
  '2026-07-29-v1',
  'How we use your health information',
  $sched_a$## About this document
This is TarragonHealth's Data Processing Consent — Schedule A of our legal documentation. Version 2026-07-29-v1, published 29 July 2026. This document is currently in draft and pending final review by our legal counsel; some details (marked in brackets) are still being finalised.

## Who we are
TarragonHealth ("TarragonHealth", "we", "us") operates a digital health coordination platform for chronic disease management, preventive health, and family care in Nigeria. We are the data controller for the personal data described in this notice.

Registered entity: [Legal Entity Name — to be confirmed]. Data Protection Officer: [to be appointed and confirmed].

If you have questions about this notice or how we handle your data, contact us at privacy@tarragonhealth.ng, or write to our Data Protection Officer at the address above.

## What personal data we collect
We collect the information you give us directly and the information generated by using the platform.

• Identity and contact details — name, date of birth, sex, phone number, email, state/city/area.

• Account and family information — your role on the platform, and, if you use a family plan, the profiles of dependants you manage on their behalf.

• Health and clinical information — vitals readings, symptoms, screening and vaccination records, lab and screening results, medications, care plans, mental-health screening answers, device and wearable readings, consultation notes, and messages with your care team.

• Payment information — subscription and order history, and payment references from our payment processors. We do not store your full card number; that is handled directly by Paystack or Stripe.

• Usage information — how you use the app and website, for security, fraud prevention, and service improvement.

## Sensitive personal data
Most of what we hold about you — your vitals, symptoms, diagnoses, medications, and results — is health information, which the Nigeria Data Protection Act 2023 classifies as sensitive personal data. We apply extra safeguards to this category of data: it is only visible to your assigned care team and to you, access is logged, and it is protected in the same way whether it was entered by you, by a clinician, or by a connected device.

## Why we process your data, and our lawful basis
We rely on more than one lawful basis, depending on the purpose.

• Delivery of healthcare — processing your clinical information to coordinate your care, alert your doctor to an abnormal result, and maintain your longitudinal health record is necessary for the provision of healthcare by a licensed clinician under a duty of confidentiality.

• Your consent — where processing is not necessary for your direct care, for example optional features, marketing communications, or sharing your data with a family sponsor or an employer/HMO wellness programme, we rely on your specific, informed consent, which you may withdraw at any time without affecting the lawfulness of processing carried out before withdrawal.

• Legal obligation — we process certain data, for example payment and tax records, to meet our obligations under Nigerian law.

• Legitimate interest — we process limited technical and usage data for security, fraud prevention, and to keep the platform working reliably, in a way that does not override your rights and interests.

## Where your data is stored, and international transfer
Your data is stored in a Postgres database operated by our infrastructure provider, Supabase, in the AWS eu-west-1 region (Ireland). We use this region because our provider does not currently offer a data centre in Nigeria or elsewhere in Africa; eu-west-1 is the nearest available region.

This means your personal data, including sensitive health information, leaves Nigeria as a routine part of how the platform runs, not as an occasional or optional event. Nigerian law requires a specific lawful mechanism before personal data is transferred outside Nigeria, such as a finding that the destination country provides an adequate level of protection, appropriate contractual safeguards, or your specific, informed consent to that transfer.

[The exact mechanism we rely on for this transfer is being finalised with our legal counsel. Until confirmed, this section should be read as a disclosure of the fact of the transfer, not a representation that a specific lawful mechanism has been finalised.]

Some of the services we use to run the platform, our payment processors, communication providers, and the systems that support clinical decision support, may also process limited data outside Nigeria, under their own data processing agreements with us.

## Automated processing and risk scoring
We use automated tools, including a rule-based Health Score, risk-assessment logic, and a machine-learning service that estimates things like cardiovascular risk and blood-pressure control, to help prioritise your care and flag results that may need attention. These tools support your care team; they do not make a final clinical decision about your diagnosis, treatment, or care without a licensed doctor reviewing it. Any decision that has a legal or similarly significant effect on you is made, or reviewed and confirmed, by a person, not by an automated system alone. You may ask us for an explanation of an automated assessment shown to you, or ask for it to be reviewed by a person.

## Who we share your data with
We share your data only as needed to provide your care and run the platform.

• Your assigned care team — the doctors, care coordinators, and clinical staff involved in your care.

• Partner laboratories, pharmacies, and specialists you choose to book with, limited to what they need to fulfil that specific order or referral.

• Your employer or HMO, where you are enrolled through a corporate or HMO programme, only in aggregated, de-identified form for programme reporting, unless you have separately and specifically consented to direct sharing of your individual results.

• Our payment processors, Paystack and Stripe, to process a payment you have initiated.

• Regulators, courts, or other authorities, where we are legally required to disclose information.

We do not sell your personal data.

## How long we keep your data
We keep your data for as long as you have an active account, and for a further period after your account closes to meet our clinical record-keeping and legal obligations.

[A formal retention schedule, with exact periods per data category, is being finalised with counsel. Until then, requests for deletion are handled case by case, applying the most conservative retention period that plausibly applies.]

## Your rights
Under Nigerian data protection law, you have the right to:

• Access the personal data we hold about you.

• Ask us to correct inaccurate or incomplete data.

• Ask us to erase your data, subject to our clinical and legal retention obligations.

• Object to, or ask us to restrict, certain processing.

• Receive a copy of your data in a portable format.

• Withdraw consent at any time, where processing is based on consent.

• Lodge a complaint with the Nigeria Data Protection Commission, or with us directly at privacy@tarragonhealth.ng.

## Security
We restrict access to your data to the staff who need it for your care, encrypt data in transit and at rest, enforce database-level access controls so that no organisation or account can see another's data, and keep an audit log of access to clinical records. No system is completely secure, and we will tell you, and where the law requires it the Nigeria Data Protection Commission, if we become aware of a breach affecting your personal data.

## Family and dependant data
If you add a family member or dependant to your account, including a child, you confirm that you have the legal authority to consent to their information being processed on their behalf, and that you will help them understand how their data is used once they are old enough to do so themselves.

## Changes to this notice
We may update this notice as the platform changes. We will show you the current version and ask you to accept it again if a material change affects how your data is used.

## Contact and complaints
Email privacy@tarragonhealth.ng with any question, request, or complaint about how we handle your data. You may also complain directly to the Nigeria Data Protection Commission.$sched_a$,
  true
),
(
  'telehealth',
  '2026-07-29-v1',
  'Consent to remote care',
  $sched_b$## About this document
This is TarragonHealth's Telehealth Consent — Schedule B of our legal documentation. Version 2026-07-29-v1, published 29 July 2026. This document is currently in draft and pending final review by our legal counsel.

## What this consent covers
This is your consent to receive clinical review, monitoring, and consultation from TarragonHealth remotely, through the app, the website, messages, and, where a video visit is booked, a video call. It is separate from, and in addition to, our data processing consent and our terms of service.

## Your care team, and how it is structured
TarragonHealth directly employs the doctors who provide your day-to-day monitoring and review. Your care may also involve non-clinical Care Coordinators who handle logistics, reminders, booking, adherence follow-up, and who never interpret a result, adjust a medication, or close a clinical escalation; anything requiring clinical judgement is routed to a doctor.

Our clinical staff work at different levels of seniority, matched to the complexity of the case in front of them. Most patients stay with a first-line doctor for routine, stable care, and a case is escalated to a more senior or specialist doctor only when it needs to be. Every doctor providing clinical review to you is registered with the Medical and Dental Council of Nigeria (MDCN), and that registration is verified before they are permitted to see patients on the platform.

Where a result or note is shown to you as reviewed by a named doctor, that reflects a real clinician who actually reviewed your case; we do not display that attribution without a corresponding record of who reviewed it and when.

## How we monitor and respond to results
If a screening or clinical result comes back abnormal, we treat that as high priority: your doctor is alerted immediately, and we target contacting you within four hours of that alert. This is a service standard we hold ourselves to, not a guarantee of a specific outcome in every case; how quickly we can reach you also depends on you being reachable.

## What remote care can and cannot do
Remote monitoring lets your care team review your readings, results, and symptoms and respond between visits, without you needing to travel for every check-in. It has real limits: your doctor cannot examine you in person, and their assessment is based on the information you provide and the readings you or your devices log. If something changes that a remote review cannot safely assess, your care team may ask you to be seen in person or refer you to a partner facility or specialist.

## Emergency care
TarragonHealth does not provide emergency care. If you are having a medical emergency, do not wait for a message or a call from us. Go to the nearest hospital or call your local emergency number immediately. The app, WhatsApp, and our doctors are not a substitute for emergency services, and no part of this platform is designed to be used in an emergency.

## Confidentiality
Your clinical information is kept confidential, consistent with the National Health Act 2014 and the MDCN's Code of Medical Ethics. It is shared with your care team on a need-to-know basis, and outside that only with your written consent, where the law requires disclosure, for example a court order, or where there is a serious threat to your life, health, or public health. See our Data Processing Consent for how we handle your data more broadly.

## Your right to information and to take part in your care
You can ask which doctor, or which level of doctor, reviewed a specific result or note. You are entitled to have your options, including tests, treatments, and referrals, explained to you in a way you can understand, along with any relevant costs, before you decide whether to go ahead.

## Your right to consent, and to refuse
You can decline any specific test, treatment, or referral we recommend. Declining one recommendation does not end your access to the rest of the platform, unless what you are declining is safety-critical, in which case we will tell you clearly why, and what the consequence of declining is.

## Withdrawing this consent
You can withdraw this consent at any time by contacting us or through your account settings. Withdrawing ends remote clinical review going forward; it does not delete your existing health record, which we keep in line with our Data Processing Consent.

## Contact
Questions about your care or this consent: support@tarragonhealth.ng.$sched_b$,
  true
),
(
  'terms_of_service',
  '2026-07-29-v1',
  'Terms of service',
  $sched_c$## About this document
This is TarragonHealth's Terms of Service — Schedule C of our legal documentation. Version 2026-07-29-v1, published 29 July 2026. This document is currently in draft and pending final review by our legal counsel.

## Acceptance of these terms
By creating a TarragonHealth account, you agree to these terms, our Data Processing Consent, and our Telehealth Consent. If you do not agree, do not use the platform.

## Eligibility and accounts
You must be at least 18 years old to open a primary account. Once you have an account, you may add family members or dependants you are legally responsible for, including children, under our family and ParentCare plans, and manage their care through your account. You are responsible for the accuracy of the information you provide, including information you enter on a dependant's behalf, and for keeping your login secure.

## What TarragonHealth is, and isn't
TarragonHealth is a coordination platform. We employ and contract the doctors and clinical staff who monitor and review your care, and we connect you to a network of independent partner laboratories, pharmacies, and specialists for tests, medication, and referrals. We do not own or operate any hospital, clinic, laboratory, or pharmacy. We are not an emergency service. Where we work with an employer or HMO, our role is care coordination and reporting; we are not an insurer, and nothing on the platform should be read as insurance underwriting or a guarantee of coverage.

## Your subscription
Plans are billed in Naira through Paystack, or in GBP/USD through Stripe if you are billed as a diaspora subscriber. The price and billing interval shown to you at checkout apply to your subscription. Your subscription automatically renews at the end of each billing period unless you cancel before the renewal date.

## Cancelling and refunds
You can cancel at any time from your account settings. Cancelling stops your subscription from renewing; you keep full access through the end of the period you have already paid for. We do not provide a partial or pro-rata refund for the unused portion of a period you cancel mid-cycle, except where required by applicable law or where we decide, at our discretion, that a billing error or a service failure attributable to us warrants one.

[Our position on refunds and cooling-off periods is being reviewed with counsel, including whether a different rule should apply to diaspora subscribers billed in GBP/USD.]

## Fees, price changes, and currency
We may change our prices. If a change affects your existing subscription, we will give you at least 30 days' notice before it takes effect, and you may cancel before the new price applies.

## Booking labs, pharmacy, and specialist services
Lab tests, pharmacy orders, home visits, and specialist referrals booked through the platform are separate, one-off charges from your subscription. Booking and paying through the platform reserves or confirms your order with the relevant partner; the partner then fulfils it according to their own availability and processes. We are not responsible for a partner's acts or omissions in fulfilling an order, though we will help you resolve a problem where we reasonably can.

## Acceptable use
You agree to provide accurate information, not to impersonate another person or misrepresent your relationship to a dependant you manage, not to misuse the platform to harass our staff or other users, and not to attempt to bypass the platform's security or access controls.

## Intellectual property
The TarragonHealth name, brand, and the software and content that make up the platform belong to us or our licensors. We grant you a personal, non-transferable licence to use the platform for your own care or the care of dependants you manage. You may not copy, resell, or build a competing service from our platform or content.

## Third-party services
The platform links to and integrates with services we do not control, including Paystack, Stripe, WhatsApp, and our partner laboratories, pharmacies, and specialists. Your use of those services is subject to their own terms, and we are not responsible for their acts, omissions, or availability.

## Disclaimers and limitation of liability
The platform is provided on an "as available" basis. To the maximum extent permitted by law, our liability to you is limited.

[The specific limitation-of-liability cap and structure is being finalised with counsel.]

## Termination
We may suspend or terminate your account if you breach these terms, do not pay a fee that is due, or engage in conduct that puts our staff, other users, or the platform at risk.

## Changes to these terms
We may update these terms as the platform changes. We will show you the current version and ask you to accept it again if a material change affects your rights or obligations.

## Governing law and disputes
These terms are governed by the laws of the Federal Republic of Nigeria.

[The specific dispute-resolution venue and mechanism is being finalised with counsel.]

Nothing in this clause limits any right you have under the Federal Competition and Consumer Protection Act 2018 to complain to the FCCPC, or your right to complain to the Nigeria Data Protection Commission under our Data Processing Consent.

## Contact
Questions about these terms: legal@tarragonhealth.ng.$sched_c$,
  true
)
on conflict (consent_type, version) do nothing;

-- ---------------------------------------------------------------------------
-- Public (anon) read of current versions only — lets the marketing site
-- render /privacy, /telehealth-consent, /terms without an authenticated
-- session, same anon-read-published-rows pattern as marketing_resources.
-- Draft/superseded versions stay authenticated-only (existing policy).
-- ---------------------------------------------------------------------------

drop policy if exists consent_versions_anon_select on public.consent_versions;
create policy consent_versions_anon_select on public.consent_versions
  for select to anon
  using (is_current);

grant select on public.consent_versions to anon;
