-- ---------------------------------------------------------------------------
-- Partner-employee and back-office roles leave private.is_org_staff.
--
-- Follows 20260729124330 (I9), which removed corporate_admin/hmo_admin from
-- private.is_org_staff after finding they satisfied 314 policies across 110
-- patient-scoped tables. That audit named the class of bug rather than one
-- instance of it: is_org_staff admits `role <> 'patient'`, so EVERY account
-- role that is not a patient inherits full clinical read access to its
-- organisation, whether or not it delivers care.
--
-- Four roles still passed it and should not:
--
--   pharmacist   — employed by a PARTNER pharmacy, not by Tarragon. Its entire
--                  surface is four SECURITY DEFINER RPCs (pharmacist_orders,
--                  pharmacist_order_allergies, pharmacist_order_medications,
--                  pharmacist_record_dispense), each scoped to a single order
--                  via private.pharmacist_partner(). Those RPCs exist
--                  specifically to confine cross-tenant PHI to one order;
--                  blanket is_org_staff access was a silent bypass of exactly
--                  the isolation they were written to enforce.
--   lab_liaison  — a Tarragon back-office employee (NOT a partner employee —
--                  see 20260720120005) who files results emailed in by labs
--                  that never log in. Needs to identify a patient and see what
--                  has been uploaded. Nothing else.
--   finance      — reaches its data through 68 SECURITY DEFINER RPCs gated by
--                  private.is_finance().
--   analyst      — reaches its data through 34 SECURITY DEFINER RPCs gated by
--                  private.is_analyst().
--
-- Because a SECURITY DEFINER function runs as its owner, every one of those
-- 106 RPCs is unaffected by RLS and therefore by this change. Verified by
-- reading each role's surface: /pharmacist, /finance and /analytics make ZERO
-- direct table reads — they are 100% RPC. Only /lab-liaison touches tables
-- directly, and only two of them, both re-granted by name below.
--
-- The UI route guard (proxy.ts) is not the boundary being fixed here. It
-- redirects one role away from another's pages, but any of these accounts can
-- present its own JWT to PostgREST directly; RLS is the only real control.
-- ---------------------------------------------------------------------------

-- 1. Name the two role classes ------------------------------------------------
-- Stated once here rather than spelled out as a role list in every policy that
-- needs it, matching private.is_institution_admin() from the I9 migration.

create or replace function private.is_scoped_access_role()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid())
      and role in ('pharmacist', 'lab_liaison', 'finance', 'analyst')
  );
$$;

comment on function private.is_scoped_access_role() is
  'True for a partner-employee (pharmacist) or back-office (lab_liaison, '
  'finance, analyst) account. Deliberately excluded from private.is_org_staff: '
  'each reaches its data through its own purpose-built SECURITY DEFINER RPCs '
  'or through a table re-granted to it by name, never through blanket '
  'care-team membership.';

create or replace function private.is_lab_liaison()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'lab_liaison'
  );
$$;

comment on function private.is_lab_liaison() is
  'The Lab Liaison Officer (20260720120005). Used to re-grant the two tables '
  'the role genuinely needs after its removal from private.is_org_staff.';

-- 2. The single structural change ---------------------------------------------
-- Same shape as I9 left it, one clause added. Every patient-scoped policy in
-- the database inherits it — including the ~90 tables whose policies are
-- generated by format() loops (see 20260705211129) rather than written out.

create or replace function private.is_org_staff(org uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid())
      and role <> 'patient'
      -- I9: an institution administrator is not care-team staff.
      and role not in ('corporate_admin', 'hmo_admin')
      -- Nor is a partner employee or a back-office account. Excluded here
      -- rather than in 314 individual policies.
      and role not in ('pharmacist', 'lab_liaison', 'finance', 'analyst')
      and (role = 'admin' or organisation_id = org)
  );
$$;

comment on function private.is_org_staff(uuid) is
  'Tarragon care-team and operations staff for an organisation: clinician, '
  'doctor, care_coordinator, and the admin super-user. Institution admins '
  '(I9), partner employees and back-office roles are excluded and are served '
  'by named grants or their own SECURITY DEFINER RPCs instead.';

-- 3. Give the lab liaison back exactly what its job needs ----------------------
-- The exclusion above is total, so the two surfaces the liaison actually uses
-- are re-granted by name. Neither is a clinical record: one is patient
-- identity (needed to file a result against the right person), the other is
-- the queue of result files the liaison itself uploads.
--
-- pharmacist, finance and analyst get NO re-grant. Their surfaces were read
-- end to end and contain no direct table access at all.

-- 3a. Patient identity. Restricted to patient rows in the liaison's own
-- organisation — tighter than the blanket org-staff read it replaces, and
-- exactly what apps/web/src/app/(dashboard)/lab-liaison/page.tsx and
-- apps/web/src/lib/lab-results/actions.ts query (both filter role = 'patient').
-- That second call site is the app's real cross-tenant gate on upload: it
-- confirms the target patient is visible to the caller before the service-role
-- client writes the file, so this clause is load-bearing, not cosmetic.
drop policy if exists profiles_select on public.profiles;

create policy profiles_select on public.profiles
  for select to authenticated
  using (
    id = (select auth.uid())
    or private.is_admin()
    or (organisation_id is not null and private.is_org_staff(organisation_id))
    or (
      private.is_lab_liaison()
      and role = 'patient'
      and organisation_id is not null
      and organisation_id = private.current_org_id()
    )
    or exists (
      select 1 from public.care_plans cp
      where cp.assigned_clinician_id = profiles.id
        and cp.patient_id = (select auth.uid())
    )
    or exists (
      select 1 from public.profile_access pa
      where pa.profile_id = profiles.id
        and pa.grantee_user_id = (select auth.uid())
    )
  );

-- 3b. The uploaded-results feed. SELECT only, deliberately:
--   * INSERT is performed by the service-role client (the file must land under
--     the patient's storage folder, which a staff session may not write), so
--     the liaison never needs the INSERT policy.
--   * UPDATE is the clinician-review stamp, gated in the server action on an
--     active clinical_staff row — which a liaison never has.
drop policy if exists lab_result_documents_select on public.lab_result_documents;

create policy lab_result_documents_select on public.lab_result_documents
  for select to authenticated
  using (
    patient_id = (select auth.uid())
    or private.is_org_staff(organisation_id)
    or (private.is_lab_liaison() and organisation_id = private.current_org_id())
  );

-- 4. Assertions ----------------------------------------------------------------

do $$
declare
  v_role   text;
  v_org    uuid;
  v_id     uuid;
  v_leaky  text;
  v_count  integer;
begin
  -- The exclusion actually took.
  if (select prosrc from pg_proc p join pg_namespace n on n.oid = p.pronamespace
      where n.nspname = 'private' and p.proname = 'is_org_staff') not like '%pharmacist%' then
    raise exception 'is_org_staff was not rewritten with the scoped-access exclusion';
  end if;

  -- I9 must not have been undone by this rewrite.
  if (select prosrc from pg_proc p join pg_namespace n on n.oid = p.pronamespace
      where n.nspname = 'private' and p.proname = 'is_org_staff') not like '%corporate_admin%' then
    raise exception 'the I9 institution exclusion was lost';
  end if;

  -- Prove it behaves rather than trusting the text: every real account in the
  -- four roles must now fail the is_org_staff predicate for its OWN org.
  for v_role, v_org, v_id in
    select p.role::text, p.organisation_id, p.id
    from public.profiles p
    where p.role::text in ('pharmacist', 'lab_liaison', 'finance', 'analyst')
      and p.organisation_id is not null
  loop
    if (select exists (
          select 1 from public.profiles
          where id = v_id and role <> 'patient'
            and role not in ('corporate_admin', 'hmo_admin')
            and role not in ('pharmacist', 'lab_liaison', 'finance', 'analyst')
            and (role = 'admin' or organisation_id = v_org)
        )) then
      raise exception 'a % account still satisfies the is_org_staff predicate', v_role;
    end if;
  end loop;

  -- Care-team staff must be UNAFFECTED. If this fires, the narrowing went too
  -- far and real clinical features are about to go blank.
  select p.organisation_id, p.id into v_org, v_id
  from public.profiles p
  where p.role::text in ('clinician', 'doctor', 'care_coordinator')
    and p.organisation_id is not null
  limit 1;

  if v_id is not null then
    if not (select exists (
          select 1 from public.profiles
          where id = v_id and role <> 'patient'
            and role not in ('corporate_admin', 'hmo_admin')
            and role not in ('pharmacist', 'lab_liaison', 'finance', 'analyst')
            and (role = 'admin' or organisation_id = v_org)
        )) then
      raise exception 'a care-team account no longer satisfies is_org_staff — narrowing overshot';
    end if;
  end if;

  -- The whole argument for granting pharmacist/finance/analyst nothing is that
  -- their surfaces are served exclusively by SECURITY DEFINER functions, which
  -- ignore RLS. If any of them is not SECURITY DEFINER, this migration silently
  -- breaks that role's dashboard, so refuse to apply.
  select string_agg(p.proname, ', '), count(*)
    into v_leaky, v_count
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and (p.proname like 'finance\_%' or p.proname like 'analytics\_%'
         or p.proname like 'pharmacist\_%')
    and not p.prosecdef;

  if v_count > 0 then
    raise exception
      'these role RPCs are not SECURITY DEFINER and would break once the role '
      'loses is_org_staff: %', v_leaky;
  end if;

  -- Each role must still have its own gate to be served through.
  if not exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                 where n.nspname = 'private' and p.proname = 'pharmacist_partner') then
    raise exception 'private.pharmacist_partner() is missing — pharmacist has no access path left';
  end if;
  if not exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                 where n.nspname = 'private' and p.proname = 'is_finance') then
    raise exception 'private.is_finance() is missing — finance has no access path left';
  end if;
  if not exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                 where n.nspname = 'private' and p.proname = 'is_analyst') then
    raise exception 'private.is_analyst() is missing — analyst has no access path left';
  end if;

  -- The liaison's two re-granted surfaces must be reachable.
  if (select count(*) from pg_policies
      where schemaname = 'public'
        and tablename in ('profiles', 'lab_result_documents')
        and coalesce(qual, with_check) like '%is_lab_liaison%') <> 2 then
    raise exception 'the lab-liaison policies were not both restored';
  end if;

  -- profiles_select must not have lost any of its pre-existing clauses.
  if (select qual from pg_policies
      where schemaname = 'public' and tablename = 'profiles'
        and policyname = 'profiles_select') not like '%profile_access%' then
    raise exception 'profiles_select lost its profile_access consent clause';
  end if;
  if (select qual from pg_policies
      where schemaname = 'public' and tablename = 'profiles'
        and policyname = 'profiles_select') not like '%assigned_clinician_id%' then
    raise exception 'profiles_select lost its assigned-clinician clause';
  end if;
end $$;
