-- Tarragon Health — DB-backed /resources content hub (founder ask: articles
-- must be addable via admin, no deploy).
--
-- marketing_resources is a GLOBAL, public catalogue (like lifestyle_programmes
-- / health_education_content, no organisation_id): published rows are readable
-- by ANON because the marketing site renders them to signed-out visitors —
-- that is the entire point of the table. Writes are admin-only. The marketing
-- pages read through a bare anon supabase-js client (no auth/platform module
-- imports), keeping the marketing/platform boundary intact; the admin editor
-- lives in the dashboard, not the marketing tree.
--
-- sections shape: [{"heading": text, "paragraphs": [text, ...]}, ...] —
-- exactly the shape the static _content/resources.ts articles used, which are
-- seeded below as the initial published library.

create table public.marketing_resources (
  id             uuid primary key default gen_random_uuid(),
  slug           text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]*$'),
  title          text not null,
  description    text not null,
  category       text not null,
  read_minutes   integer not null default 4 check (read_minutes between 1 and 60),
  related_href   text,
  related_label  text,
  sections       jsonb not null default '[]'::jsonb,
  is_published   boolean not null default false,
  sort_order     integer not null default 100,
  updated_by     uuid references public.profiles (id) on delete set null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index marketing_resources_published_idx
  on public.marketing_resources (category, sort_order)
  where is_published;

create trigger marketing_resources_set_updated_at
  before update on public.marketing_resources
  for each row execute function private.set_updated_at();

alter table public.marketing_resources enable row level security;

-- Public read of published articles only; admins see and manage everything.
create policy marketing_resources_public_select on public.marketing_resources
  for select to anon, authenticated
  using (is_published or private.is_admin());
create policy marketing_resources_admin_write on public.marketing_resources
  for all to authenticated
  using (private.is_admin())
  with check (private.is_admin());

grant select on public.marketing_resources to anon;
grant select, insert, update, delete on public.marketing_resources to authenticated;
insert into public.marketing_resources
  (slug, title, description, category, read_minutes, related_href, related_label, sections, is_published, sort_order)
values
('normal-blood-pressure', 'What is a normal blood pressure — and when should you worry?', 'What the two numbers mean, what counts as high in adults, and why one raised reading is not a diagnosis.', 'Blood pressure', 4, '/hypertension', 'How Tarragon manages hypertension', '[{"heading": "The two numbers, in plain language", "paragraphs": ["A blood pressure reading has two numbers, written like 120/80. The first (systolic) is the pressure in your arteries when your heart squeezes; the second (diastolic) is the pressure between beats, when the heart rests. Both matter.", "For most adults, a reading under 130/85 at rest is in a healthy range. Readings that stay at 140/90 or higher, measured properly on separate days, are what doctors call hypertension \u2014 high blood pressure."]}, {"heading": "Why one high reading is not a diagnosis", "paragraphs": ["Blood pressure moves all day. Stress, caffeine, a rushed walk into the pharmacy, even the measurement itself (''white-coat effect'') can push a single reading up. That is why no good clinician diagnoses hypertension from one number.", "What matters is the pattern: several readings, taken while rested, on different days. A home blood-pressure monitor \u2014 used correctly, seated, arm supported \u2014 often gives a truer picture than an occasional clinic check."]}, {"heading": "Why it matters so much in Nigeria", "paragraphs": ["Hypertension is very common among Nigerian adults and is a leading driver of stroke, heart failure and kidney disease \u2014 yet it usually has no symptoms at all. Feeling fine tells you nothing about your blood pressure. The only way to know is to measure."]}, {"heading": "What to actually do", "paragraphs": ["If you have never checked, check \u2014 at a pharmacy, a lab, or with a home cuff. If your readings sit at 140/90 or above more than once, see a doctor; hypertension is very treatable, and treatment is far cheaper than a stroke.", "If you are already diagnosed, the goal is control, not just tablets: take medicines consistently, cut salt, and keep measuring so you and your doctor can see whether the plan is working."]}]'::jsonb, true, 10),
('hba1c-explained', 'HbA1c: the 3-month sugar test, explained simply', 'Why doctors trust HbA1c more than a single fasting sugar, what the percentages mean, and how often to test.', 'Diabetes', 4, '/diabetes', 'How Tarragon manages diabetes', '[{"heading": "What HbA1c actually measures", "paragraphs": ["Sugar in your blood sticks to haemoglobin, the protein inside red blood cells. Because red cells live about three months, measuring how much sugar is stuck to them (HbA1c) reveals your average blood sugar over the past two to three months \u2014 not just this morning.", "That is why a single fasting glucose can look fine on a good day while HbA1c tells the fuller story."]}, {"heading": "Reading your result", "paragraphs": ["As a widely used guide: below 5.7% is in the normal range; 5.7\u20136.4% is called prediabetes \u2014 a warning zone where change still prevents diabetes; 6.5% or higher on a proper laboratory test supports a diagnosis of diabetes.", "If you already live with diabetes, your doctor will set a personal target \u2014 often around 7% \u2014 balancing control against the risk of sugar going too low. Your target is a conversation, not a universal number."]}, {"heading": "How often should you test?", "paragraphs": ["If you have diabetes, HbA1c every three to six months shows whether your plan is working. If you are in the prediabetes zone, a yearly test tracks which direction you are moving. If you have risk factors \u2014 family history, excess weight, previous high readings \u2014 ask about testing rather than waiting for symptoms."]}, {"heading": "The point of the number", "paragraphs": ["HbA1c is not a grade on your character; it is feedback. Food, movement, medicines and stress all move it, and it responds within months. People bring it down every day \u2014 usually with a mix of small consistent changes and the right prescription, reviewed regularly."]}]'::jsonb, true, 20),
('lower-blood-pressure-naturally', 'Five changes that genuinely lower blood pressure', 'Salt, weight, movement, alcohol and sleep — what the evidence supports, and what it can and can''t replace.', 'Blood pressure', 5, '/hypertension', 'Hypertension care at Tarragon', '[{"heading": "First, an honest frame", "paragraphs": ["Lifestyle change genuinely lowers blood pressure \u2014 for many people by enough to matter. But if your readings are high, lifestyle work is usually a partner to medication, not a replacement for it. Never stop a prescribed medicine on your own; blood pressure rebounds quietly."]}, {"heading": "1. Cut the salt you can''t see", "paragraphs": ["Most excess salt is not from your salt spoon \u2014 it hides in seasoning cubes, instant noodles, processed and tinned foods, and suya spice mixes. Halving these often does more than banning table salt. Aim to cook more from fresh ingredients and taste before you season."]}, {"heading": "2. Lose weight if you carry extra", "paragraphs": ["Blood pressure tracks body weight closely. Even a 5% weight loss \u2014 4 kg for an 80 kg person \u2014 measurably lowers readings for most people. Slow and sustained beats dramatic and temporary."]}, {"heading": "3. Move most days", "paragraphs": ["About 30 minutes of brisk walking most days lowers blood pressure on its own, independent of weight loss. It does not require a gym; it requires a route and a habit."]}, {"heading": "4 & 5. Alcohol and sleep", "paragraphs": ["Regular heavy drinking raises blood pressure directly \u2014 cutting down brings it back. And short, broken sleep pushes pressure up over time; snoring badly enough to gasp or choke is worth mentioning to a doctor, as sleep apnoea quietly drives resistant hypertension.", "Measure at home while you make these changes. Seeing your own numbers fall is the strongest motivation there is."]}]'::jsonb, true, 30),
('diabetes-early-signs', 'Early signs of diabetes — and who should get tested', 'The symptoms people miss, why many have no symptoms at all, and the risk factors that make testing worth it.', 'Diabetes', 4, '/diabetes', 'Diabetes care at Tarragon', '[{"heading": "The signs people notice late", "paragraphs": ["Classic warning signs include being unusually thirsty, urinating more than normal (especially at night), losing weight without trying, blurred vision, wounds that heal slowly, and repeated skin or urine infections. Any of these deserves a blood-sugar test, not a wait-and-see."]}, {"heading": "The uncomfortable truth: many people feel nothing", "paragraphs": ["Type 2 diabetes builds gradually, and the body adapts. Many people live with raised sugar for years before diagnosis \u2014 often until a complication shows up first. Feeling fine is not evidence your sugar is fine."]}, {"heading": "Who should test even without symptoms", "paragraphs": ["Testing is worth it if any of these apply: a parent or sibling with diabetes; age above 40; excess weight, especially around the waist; high blood pressure; diabetes in a past pregnancy or a baby over 4 kg; or previous borderline readings. The more that apply, the stronger the case.", "The test itself is simple \u2014 a fasting glucose or an HbA1c at any decent laboratory. It is one of the cheapest pieces of information about your future you can buy."]}, {"heading": "If the result comes back high", "paragraphs": ["A raised result is a starting line, not a sentence. Prediabetes reversed with food, movement and weight change is routine. Diagnosed diabetes managed early and consistently is compatible with a long, normal life \u2014 the complications come from years of unmanaged sugar, not from the diagnosis itself."]}]'::jsonb, true, 40),
('weight-bmi-waist', 'Is my weight a health problem? BMI, waist size, and what actually helps', 'How to read BMI honestly, why waist circumference matters, and what sustainable weight care looks like.', 'Weight', 5, '/obesity', 'The Tarragon obesity programme', '[{"heading": "BMI: useful, imperfect", "paragraphs": ["BMI is your weight in kilograms divided by your height in metres squared. As a broad guide for adults: 18.5\u201324.9 is the healthy range, 25\u201329.9 is overweight, and 30 or above is classed as obesity. It is a screening tool, not a verdict \u2014 a muscular person can score ''overweight'' while carrying little fat."]}, {"heading": "Why your waist tells you more", "paragraphs": ["Fat stored around the organs \u2014 the belly, not the hips \u2014 is what drives diabetes, hypertension and heart disease risk. A waist above roughly 94 cm for men or 80 cm for women signals raised risk even when BMI looks moderate. A tape measure is a better early-warning tool than a mirror."]}, {"heading": "What does not work", "paragraphs": ["Crash diets, teas, waist trainers and ''flat tummy'' products do not produce lasting fat loss \u2014 most produce a rebound. Weight that comes off in weeks tends to come back with interest, because nothing about daily life actually changed."]}, {"heading": "What does", "paragraphs": ["The boring, proven combination: modest calorie reduction you can sustain, protein and fibre that keep you full, 30 minutes of movement most days, sleep, and \u2014 this is the part most people skip \u2014 tracking, so the trend is visible. A 5\u201310% loss held for a year improves blood pressure, sugar and cholesterol measurably.", "If your BMI is 30+ or your weight comes with raised sugar or pressure, this is a medical matter that deserves a doctor''s structured support, not a willpower verdict. That is exactly what a managed programme is for."]}]'::jsonb, true, 50),
('annual-health-check-guide', 'The annual health check: what it should actually include', 'Which tests earn their place in a yearly screen, by age and risk — and why the follow-up matters more than the tests.', 'Screening', 5, '/prevention', 'Preventive care at Tarragon', '[{"heading": "Why screen at all when you feel fine", "paragraphs": ["The conditions that shorten most adult lives \u2014 hypertension, diabetes, kidney disease, some cancers \u2014 are silent for years and cheap to manage when caught early. A yearly check exists to catch them in the silent phase, when your options are widest."]}, {"heading": "The core, for most adults", "paragraphs": ["Blood pressure. Blood sugar (fasting glucose or HbA1c). A lipid panel (cholesterol). Weight and waist. Urinalysis (an early kidney and diabetes window). These five cover the biggest, most treatable risks and cost little."]}, {"heading": "Added by age and history", "paragraphs": ["From the 40s onward: an ECG and a fuller cardiovascular risk review. For women: cervical screening from the mid-20s and breast checks from 40. For men from 45: a prostate conversation with a doctor \u2014 informed, not automatic. Family history of any of these moves the start dates earlier."]}, {"heading": "The part most checkups get wrong", "paragraphs": ["A stack of results with no follow-up is theatre. The value is in what happens next: someone explains each result, an abnormal finding triggers an actual plan, and next year''s numbers get compared to this year''s. When you book any screening, the question to ask is not ''which tests?'' but ''who follows up?''"]}]'::jsonb, true, 60),
('cholesterol-explained', 'Cholesterol results, decoded: LDL, HDL and the number nobody mentions', 'What a lipid panel measures, which number matters most, and when cholesterol needs treating.', 'Cholesterol', 4, '/chronic-care', 'Chronic care at Tarragon', '[{"heading": "The four numbers on the report", "paragraphs": ["Total cholesterol is everything added together. LDL is the ''delivery'' cholesterol that, in excess, builds up in artery walls \u2014 the one treatment usually targets. HDL is the ''cleanup'' fraction, where higher is generally better. Triglycerides are circulating fat, sensitive to sugar, alcohol and weight."]}, {"heading": "The number nobody mentions: non-HDL", "paragraphs": ["Subtract HDL from total cholesterol and you get non-HDL cholesterol \u2014 everything capable of clogging arteries in one figure. Many clinicians now consider it a better single measure than LDL alone, and it needs no extra test: it is arithmetic on results you already have."]}, {"heading": "There is no single ''bad'' threshold", "paragraphs": ["Whether a cholesterol level needs treatment depends on your whole cardiovascular risk \u2014 age, blood pressure, smoking, diabetes, family history \u2014 not the number in isolation. The same LDL can be acceptable in one person and urgent in another who has already had a heart problem.", "That is why good care assesses total risk and sets a personal target, rather than reacting to a lab report line by line."]}, {"heading": "If yours is raised", "paragraphs": ["Diet shifts (less fried and processed food, more fibre), weight loss and movement all help, and for people at meaningful risk, statins are among the best-evidenced, most cost-effective medicines in existence. The right answer is a risk conversation with a doctor \u2014 ideally one who will still be watching the trend next year."]}]'::jsonb, true, 70)
on conflict (slug) do nothing;
-- (seed rows above generated from the retired static _content/resources.ts library)
