-- Local/CI-only fix-forward, NOT a functional migration -- same rationale
-- family as the other backdated fix-forward migrations in this history.
--
-- 20260810032858_diabetes_quality_metrics_g19_extend.sql's own
-- `create or replace view public.diabetes_quality_metrics ...` fails on a
-- fresh replay with:
--   ERROR: cannot change name of view column "target_set" to
--   "complete_complication_screen" (SQLSTATE 42P16)
-- Postgres allows CREATE OR REPLACE VIEW to append new output columns at
-- the end, but not insert one in the middle of the existing column list --
-- this migration's new complete_complication_screen column lands before
-- target_set in the SELECT list, shifting every column after it out of
-- position relative to 20260720170000_diabetes_quality_metrics.sql's
-- original definition.
--
-- Not a fresh-replay-only issue in the abstract (the same positional rule
-- applies on live too), but the live project's current view definition
-- evidently already accommodates this -- either reconciled directly against
-- the live database at some point (this project's established pattern for
-- out-of-band DB state, see 20260810030619's header for another instance)
-- or the two migrations were applied in a sequence this repo's committed
-- history doesn't fully capture. Whichever it is, editing either historical
-- migration would create exactly the committed-vs-applied drift CLAUDE.md's
-- standing lessons warn against.
--
-- Dropping the view immediately before its real redefinition sidesteps the
-- positional-rename rule entirely: the very next statement's own
-- `create or replace view` then acts as a genuine CREATE (nothing to
-- replace), which has no column-position constraint, and produces exactly
-- the column set and order that migration always intended. Safe on live:
-- no other migration in this history references diabetes_quality_metrics
-- (confirmed by grep), and the owning migration re-issues its own
-- `grant select ... to authenticated` immediately after, so no privilege is
-- lost in between.
drop view if exists public.diabetes_quality_metrics;
