-- Tarragon Health
-- The live consent_versions rows real patients were agreeing to
-- (data_processing/telehealth 2026-07-29-v1, terms_of_service 2026-07-30-v1)
-- described a narrower, cardiometabolic-only product ("Control"/"Concierge"
-- tiers, a two-model doctor-accountability switch, WHO HEARTS as the sole
-- protocol) that was superseded within a day of being specified — see
-- docs/legal/cover-memo-to-counsel.md's "What changed since v2" section for
-- the full account. Real patients were consenting to a description of a
-- product that is not the one they were using. This migration retires those
-- three rows and publishes v3, matching docs/legal/schedule-{a,b,c}-*
-- (the canonical source for this text — edit there first, then re-sync).
-- Still explicitly marked draft/pending-counsel-review, same as its
-- predecessor — this is a correction of fact, not a claim of legal sign-off.
--
-- Applied live via execute_sql (not apply_migration) because the body text
-- is large and this file exists to keep the repo's migration history
-- consistent with what actually ran, matching this codebase's established
-- reconciliation convention for anything applied outside apply_migration.
-- Content is reproduced in full below so a fresh environment gets the same
-- rows a `supabase db reset` would apply.

update public.consent_versions
set is_current = false
where consent_type in ('data_processing', 'telehealth', 'terms_of_service')
  and is_current = true
  and version <> '2026-07-31-v1';

insert into public.consent_versions (consent_type, version, title, body, is_current, published_at)
values (
  'data_processing', '2026-07-31-v1', 'How we use your health information',
  $body$## About this document
This is TarragonHealth's Data Processing Consent — Schedule A of our legal documentation. Version 2026-07-31-v1, published 31 July 2026. This document is currently in draft and pending final review by our legal counsel; some details (marked in brackets) are still being finalised.

## Who we are
Tarragon Health Ltd (RC 9702108) ("TarragonHealth", "we", "us") operates a digital-first chronic disease, preventive health, and care-coordination platform in Nigeria, connecting patients with doctors, labs, pharmacies, specialists, employers, and HMOs. We are the data controller for the personal data described in this notice.

Data Protection Officer: [DPO name and contact — to be appointed and confirmed]. Nigeria Data Protection Commission (NDPC) registration status: [to be confirmed with counsel].

If you have questions about this notice or how we handle your data, contact us at privacy@tarragonhealth.ng, or write to our Data Protection Officer at the address above.

## What personal data we collect
We collect the information you give us directly, the information your care team records about you, and the information generated by using the platform.

• Identity and contact details — name, date of birth, sex, phone number, email, state and local government area of residence.

• Emergency contact — the name and phone number of a next of kin, used to reach someone on your behalf in an emergency, or, with your consent, to let them view (not edit) your record.

• Health and clinical information — vitals readings (blood pressure, glucose, weight, and others); the device you use to take them; symptoms and messages you share with your care team; medications; screening and lab results; vaccination records; and clinical notes written by your doctor.

• Wallet and payment information — subscription, Health Wallet, and order history, and payment references from Paystack or Stripe. We do not store your full card number. Where you top up your own or a family member's Health Wallet, we record the amount and the funding relationship between you.

• Device information — where you use a Bluetooth-paired reading device, its make, model, and serial number.

• Usage information — app and website activity, for security, fraud prevention, and service improvement.

## Sensitive personal data
Most of what we hold about you — your readings, symptoms, diagnoses, medications, and results — is health information, which the Nigeria Data Protection Act 2023 classifies as sensitive personal data. We apply extra safeguards to this category of data: it is only visible to your care team and to you, access is logged, and every clinical action taken on your record is written to a record you can read yourself.

## Why we process your data, and the specific consents we ask for
We rely on more than one lawful basis, depending on the purpose.

• Delivery of your care — processing your readings, symptoms, and clinical information to classify your results, alert your care team, and maintain your record is necessary for the provision of healthcare by a licensed clinician under a duty of confidentiality.

• Specific, scoped consent — for anything beyond your direct care, we ask for a specific consent, tracked individually and revocable at any time:

• Escalation contact — your consent for us to message or call you if we do not hear from you when we should. This is asked at enrolment and is required to activate your account.

• Clinical share — your consent to share your clinical information with a specific named recipient, for example a specialist you are referred to.

• Family/sponsor access — a family member, next of kin, or sponsor funding your Health Wallet may, with your separate consent, view your record or manage bookings on your behalf. Funding your care never grants this access automatically — it is a separate, two-sided request either of you can initiate and either of you can decline.

• Institution aggregate — if you are enrolled through an employer or HMO programme, your data contributes to that organisation's aggregate statistics in de-identified form regardless of this consent, because the organisation never sees anything about you individually — see "Who we share your data with" below.

• Research, anonymised — your optional consent for your anonymised data to be used in research. This is off by default. If you consent and later withdraw, we stop including you in future research exports, but we cannot recall an export already delivered before you withdrew.

• Legal obligation — we process certain data, for example payment and tax records, to meet our obligations under Nigerian law.

[Counsel to confirm this consent-scope structure is the correct lawful-basis architecture under the Act, and specifically that account activation may properly be conditioned on the "escalation contact" consent.]

## Where your data is stored, and international transfer
Your data is stored in a Postgres database operated by our infrastructure provider, Supabase, in the AWS eu-west-1 region (Ireland). We use this region because our provider does not currently offer a data centre in Nigeria or elsewhere in Africa; eu-west-1 is the nearest available region.

This means your personal data, including sensitive health information, leaves Nigeria as a routine part of how the platform runs, not as an occasional or optional event. This is the single highest-priority open item in our own legal review. Nigerian law requires a specific lawful mechanism before personal data is transferred outside Nigeria.

Separately, a summarising step assisting your doctor's own review (see "Automated processing" below) sends a limited, structured extract of your record — never your free-text notes — to a second processor, Anthropic, whose infrastructure is also outside Nigeria.

[The exact mechanism we rely on for each of these two transfers is being finalised with our legal counsel. Until confirmed, this section should be read as a disclosure of the fact of both transfers, not a representation that a specific lawful mechanism has been finalised for either.]

## Automated processing
Every reading you log is automatically classified against a clinical protocol appropriate to its type — this always happens, even for a normal reading, so nothing is silently skipped. Separately, an AI model may draft a plain-language summary of your record for your doctor to review before they act on your case — it never diagnoses, never closes a case, never prescribes, and every summary is labelled as AI-drafted and not yet reviewed until a doctor has actually looked at it. A result classified urgent or emergency can only be closed by your doctor after they have spoken with you directly by phone or a live in-app conversation — it cannot be closed from a written note alone. You may ask us for an explanation of any automated assessment shown to you.

## Who we share your data with
We share your data only as needed to provide your care and run the platform.

• Your care team — the doctors and coordinators involved in your care.

• A specific person or organisation you have separately consented to share with — see "Clinical share" and "Family/sponsor access" above.

• Your employer or HMO, where you are enrolled through their programme, only as aggregate statistics with no individual identified — any figure drawn from too few people is withheld rather than shown. We tell every patient plainly: TarragonHealth does not share individual health records with your employer.

• Our payment processors, Paystack and Stripe, to process a payment you have initiated, and (for a limited, structured extract only) Anthropic, to draft a doctor-facing summary — see "Automated processing" above.

• Regulators, courts, or other authorities, where we are legally required to disclose information.

• Anonymised research exports, only for patients who have separately opted in — see "Research, anonymised" above — built so no individual can be re-identified from the output.

We do not sell your personal data.

## How long we keep your data
We keep your data for as long as you have an active enrolment, and for a further period after that to meet our clinical record-keeping and legal obligations.

[A formal retention schedule, with exact periods per data category, is being finalised with counsel. Until then, requests for deletion are handled case by case, applying the most conservative retention period that plausibly applies.]

## Your rights
Under Nigerian data protection law, you have the right to:

• Access the personal data we hold about you, and export it yourself at any time — this works from your first login and is never conditional on your subscription or payment being up to date.

• Ask us to correct inaccurate or incomplete data.

• Ask us to erase your data, subject to our clinical and legal retention obligations.

• Object to, or ask us to restrict, certain processing, and withdraw any of the specific consents listed above at any time.

• Lodge a complaint with the Nigeria Data Protection Commission [contact details, to be confirmed], or with us directly at privacy@tarragonhealth.ng.

## Security
We restrict access to your data to the staff who need it for your care, encrypt data in transit and at rest, and keep an immutable log of every access to and change of your clinical record. No system is completely secure, and we will tell you and, where the law requires it, the NDPC, if we become aware of a breach affecting your personal data.

## Guardian and dependant data
If you enrol a child under 18 as your dependant, you are their guardian for the purposes of this notice: you confirm you have the legal authority to consent to their information being processed, and you are responsible for the accuracy of what you record on their behalf. Each person, including a minor, has their own individually-structured record — we do not offer a shared or household account.

[Counsel to confirm the Act's threshold for "child" data requiring guardian consent, and that this dependant-enrolment mechanism satisfies it.]

## Changes to this notice
We may update this notice as the platform changes. We will show you the current version and ask you to accept it again if a material change affects how your data is used.

## Contact and complaints
Email privacy@tarragonhealth.ng with any question, request, or complaint about how we handle your data. You may also complain directly to the Nigeria Data Protection Commission.$body$,
  true, now()
);

insert into public.consent_versions (consent_type, version, title, body, is_current, published_at)
values (
  'telehealth', '2026-07-31-v1', 'Consent to remote care',
  $body$## About this document
This is TarragonHealth's Telehealth Consent — Schedule B of our legal documentation. Version 2026-07-31-v1, published 31 July 2026. This document is currently in draft and pending final review by our legal counsel.

## What this consent covers
This is your consent to receive clinical monitoring, classification, and review from TarragonHealth remotely, and to be contacted by phone, message, or in the app as part of that care. It is separate from, and in addition to, our data processing consent and our terms of service.

## Your care team
Your care is provided by doctors registered with the Medical and Dental Council of Nigeria (MDCN), whose registration is verified before they can see patients and checked continuously afterwards — a doctor whose registration or indemnity cover lapses is automatically suspended from seeing patients overnight, with no manual step required. TarragonHealth staffs care across five levels of clinical seniority, so a case is handled by whoever's judgement it actually needs: a first-line doctor reviews routine, stable readings under protocol; a more senior doctor initiates new medications or adjusts a dose; and the most senior doctors handle complex cases, set referral urgency, and own the clinical protocols everyone else works under. Non-clinical coordinators may also be involved in your care — they follow up if we haven't heard from you and help with logistics, and can see your progress record, but they cannot read your clinical notes, interpret a result, adjust your medication, or give clinical advice. Anything clinical is always handled by a doctor.

Every clinical note you can read shows the treating doctor's name and MDCN number.

## How your results are classified and how we respond
Every reading you log is classified, automatically, against a clinical protocol appropriate to its type — even a normal reading gets a record, so nothing is silently skipped. Separately, an AI model may draft a plain-language summary of your record to help your doctor prepare for your case — it never classifies a result itself, never diagnoses, and never closes a case; a summary is always labelled as AI-drafted until a doctor has actually reviewed it.

How quickly we respond depends on the pathway and how a result is classified — a routine screening result and a red-flagged home blood-pressure reading genuinely carry different urgency, so response times are not a single flat table. As a general guide:

• Routine findings are typically reviewed within days, as part of a batch.

• Findings needing attention but not urgent are typically actioned within 24–48 hours.

• Urgent findings typically get a phone or video call within hours, not a text message alone.

• Emergency findings get immediate, multi-channel contact, and if we cannot reach you, we document an attempt to reach your emergency contact.

A finding classified as an emergency cannot be closed on a written note alone — your doctor must have completed a real, live phone or video conversation with you first before the case can be marked resolved. These are service standards we hold ourselves to, not guarantees of a specific outcome in every case — how quickly we can reach you also depends on you being reachable.

## How we communicate with you
Different channels carry different kinds of information, on purpose:

• The app is your record — all clinical conversation, your results, your care plan, and your consent history live here.

• A phone or video call is how clinical judgement is delivered — if something in your results needs discussing, a clinician or coordinator calls you. Increasingly, this happens through a masked-number system so neither your number nor theirs is exposed to the other, and the call is logged to your record.

• SMS is used for urgent backup, and as the primary channel if you've told us you don't use a smartphone.

• WhatsApp is notification-only — a short message telling you a result is ready or a check-in is due, so you open the app. It never contains a specific number, result, diagnosis, or medication name, and this is enforced by our systems, not just our policy. You may message your doctor on WhatsApp for support, and they may reply there too — but this is a human reading and answering your message directly, never an automated system parsing what you send into a platform action.

• Email carries documents — receipts, reports, and copies of your consent records.

## What remote monitoring can and cannot do
Remote monitoring lets your care team review your readings and respond between visits, without you needing to travel for every check. It has real limits: your doctor cannot examine you in person, and their assessment is based on the readings and information you provide. If something needs an in-person assessment, your care team will tell you and refer you appropriately — including, where relevant, to one of our partner labs, pharmacies, or specialists.

## Emergency care
TarragonHealth does not provide emergency care. If you are having a medical emergency, do not wait for a message or a call from us. Go to the nearest hospital or call [Nigeria's emergency line — exact number to be confirmed] immediately. No part of this platform is designed to be used in an emergency.

## Confidentiality
Your clinical information is kept confidential. It is shared with your care team on a need-to-know basis, and outside that only with your specific consent — including a family member or sponsor you have separately consented to give view access to — where the law requires disclosure, or where there is a serious threat to your life, health, or public health. See our Data Processing Consent for how we handle your data more broadly.

## Your right to information and to take part in your care
Every message and note tells you who is speaking to you and their MDCN number where relevant. You can see every clinical action taken on your record, in plain language, at any time.

## Your right to consent, and to refuse
You can decline a specific recommendation. Declining does not end your access to the rest of the platform, unless what you are declining is safety-critical, in which case we will tell you clearly why.

## Withdrawing this consent
You can withdraw this consent at any time. Withdrawing ends remote clinical review going forward; it does not delete your existing health record, which we keep in line with our Data Processing Consent.

## Contact
Questions about your care or this consent: support@tarragonhealth.ng.$body$,
  true, now()
);

insert into public.consent_versions (consent_type, version, title, body, is_current, published_at)
values (
  'terms_of_service', '2026-07-31-v1', 'Terms of service',
  $body$## About this document
This is TarragonHealth's Terms of Service — Schedule C of our legal documentation. Version 2026-07-31-v1, published 31 July 2026. This document is currently in draft and pending final review by our legal counsel.

## Acceptance of these terms
By enrolling with TarragonHealth, you agree to these terms, our Data Processing Consent, and our Telehealth Consent. If you do not agree, do not use the platform.

## Eligibility and accounts
You must be at least 18 years old to hold your own account. An adult may enrol a child under 18 as their dependant and manage their care, under our Guardian and dependant data terms. Each person, including a minor, has their own individually-structured account — we do not offer a shared household or family account or a multi-person discount. Separately, you may name a next of kin who can be contacted in an emergency and, with your consent, view (not edit) your record, and — for an adult who wants help managing their own care — you may set up a two-sided arrangement letting another adult manage bookings on your behalf; either of you can end this at any time. You are responsible for the accuracy of the information you provide, including anything you record on a dependant's behalf, and for keeping your login secure.

## What TarragonHealth is, and isn't
TarragonHealth is a digital-first chronic disease, preventive health, and care-coordination platform: we measure your readings, classify them against a clinical protocol, connect you with a doctor when something needs attention, and coordinate labs, pharmacies, and specialist referrals on your behalf. We do not own or operate any hospital, clinic, laboratory, or screening facility — every lab, pharmacy, and specialist you use through the platform is an independent partner. We are not an emergency service — see our Telehealth Consent. We are not an insurer: nothing on the platform is capitation, claims cover, or any form of risk transfer, and where we bill an organisation for its members' access, that billing is a service fee, never a per-member premium.

## Individual and organisational access
You can enrol and pay for TarragonHealth directly. You may also be enrolled through an employer or HMO that covers your access — if so, that organisation only ever sees aggregate statistics about its whole covered group, never anything about you individually (see our Data Processing Consent).

[Where TarragonHealth sells to an organisation directly, that relationship is expected to be governed by a separate commercial agreement with the organisation, not by these terms.]

## Your subscription
All plans are priced in Naira; the same plan costs the same amount whichever way you pay, whether by a Nigerian payment method or an international card. We do not operate a separate foreign-currency price list. Your subscription automatically renews at the end of each billing period unless you turn off auto-renewal before the renewal date; turning off auto-renewal doesn't end your access early, it just stops the next charge.

## The Health Wallet
You may hold a Health Wallet balance, funded by you or, with your consent, by a family member or sponsor — including one based abroad. A wallet top-up is spendable within the platform on bookings and orders; it is not a bank account and is not withdrawable as cash. To limit how large an unverified wallet balance can grow, we apply a lower balance ceiling by default, raised once you complete an identity check. [The wallet's exact regulatory status is being confirmed with counsel.]

## Held payments for doctor video visits
A paid video visit with a doctor works differently from a subscription charge: your payment is held by us at the time you request the visit, and only goes through once a doctor accepts the request — a visit is never automatic, and depends on doctor availability. If no doctor accepts your request within a set window, or a doctor declines it, your payment is refunded.

## Cancelling and refunds
You can cancel a subscription at any time from your account settings. Cancelling stops it from renewing; you keep full access through the end of the period you have already paid for. We do not provide a partial or pro-rata refund for the unused portion of a period you cancel mid-cycle, except where required by applicable law, where we decide, at our discretion, that a billing error or a service failure attributable to us warrants one, or as described above for a held video-visit payment that is never accepted.

[Counsel to confirm whether Nigerian consumer protection law (the FCCPC framework) requires a cooling-off period or a different refund position than the one stated above.]

## Your monitoring device
Where you purchase a Bluetooth-paired monitoring device (a blood-pressure cuff, glucometer, or similar) through the platform, we will tell you clearly at the point of purchase whether it is sold to you outright or provided on some other basis. If your device is faulty, tell us — a device we cannot trust to give you a real reading undermines the reason we sold it to you.

## Fees and price changes
We may change our prices. If a change affects your existing subscription, we will give you at least 30 days' notice before it takes effect, and you may cancel before the new price applies.

## Referral rewards
If you refer someone who joins TarragonHealth using your referral link or code, both of you may receive a credit to your Health Wallet once they complete their first paid action on the platform. Reward amounts and terms may change; we'll tell you the current amount before you share your link.

## Acceptable use
You agree to provide accurate information, not to impersonate another person or misrepresent your relationship to a dependant or adult you manage, not to misuse the platform to harass our staff or other users, and not to attempt to bypass the platform's security or access controls.

## Intellectual property
The TarragonHealth name, brand, and the software and content that make up the platform belong to us or our licensors. We grant you a personal, non-transferable licence to use the platform for your own care or the care of a dependant or adult you manage. You may not copy, resell, or build a competing service from our platform or content.

## Third-party services
The platform links to and integrates with services we do not control, including Paystack, Stripe, WhatsApp, and our partner laboratories, pharmacies, and specialists. Your use of those services is subject to their own terms, and we are not responsible for their acts, omissions, or availability.

## Disclaimers and limitation of liability
The platform is provided on an "as available" basis. To the maximum extent permitted by law, our liability to you is limited.

[Counsel to set the specific limitation-of-liability cap and structure, and confirm it is enforceable for a health-adjacent consumer service under Nigerian law.]

## Termination
We may suspend or terminate your account if you breach these terms, do not pay a fee that is due, or engage in conduct that puts our staff, other users, or the platform at risk.

## Changes to these terms
We may update these terms as the platform changes. We will show you the current version and ask you to accept it again if a material change affects your rights or obligations.

## Governing law and disputes
These terms are governed by the laws of the Federal Republic of Nigeria.

[The specific dispute-resolution venue and mechanism is being finalised with counsel.]

Nothing in this clause limits any right you have under the Federal Competition and Consumer Protection Act 2018 to complain to the FCCPC, or your right to complain to the Nigeria Data Protection Commission under our Data Processing Consent.

## Contact
Questions about these terms: legal@tarragonhealth.ng.$body$,
  true, now()
);

do $$
begin
  if (select count(*) from public.consent_versions where consent_type = 'data_processing' and is_current) <> 1 then
    raise exception 'data_processing must have exactly one current version';
  end if;
  if (select count(*) from public.consent_versions where consent_type = 'telehealth' and is_current) <> 1 then
    raise exception 'telehealth must have exactly one current version';
  end if;
  if (select count(*) from public.consent_versions where consent_type = 'terms_of_service' and is_current) <> 1 then
    raise exception 'terms_of_service must have exactly one current version';
  end if;
  if not exists (
    select 1 from public.consent_versions
    where consent_type = 'terms_of_service' and is_current
      and body like '%Held payments for doctor video visits%'
  ) then
    raise exception 'sanity check failed: terms_of_service body missing expected content';
  end if;
end;
$$;
