-- Tarragon Health — Risk & Prevention Engine enhancement, 1/7
-- Add `unknown` to public.risk_level.
--
-- Founder decision 2026-08-27: missing/insufficient data must never be
-- silently interpreted as "low risk". Today private.computeRiskTiers (TS,
-- lib/rules/risk-scoring.ts) simply SKIPS emitting a row for a condition it
-- can't assess (e.g. a sex-specific condition when profile.sex isn't on
-- file) — the row never appears, which reads identically to "assessed and
-- fine" in every UI that lists risk tiers. That's the same silent-omission
-- failure mode this codebase has already ruled out elsewhere (reviewed_by/
-- reviewed_at null-gating, `doctor_tier` never defaulted — see CLAUDE.md
-- "Never infer or default a doctor_tier"). This migration adds the enum
-- value; a follow-up migration adds the confidence column, and the TS
-- engine change (separate commit) starts emitting 'unknown' instead of
-- omitting.
--
-- Standalone migration on purpose: PostgreSQL forbids using a newly added
-- enum value inside the same transaction that added it, so every migration
-- that references 'unknown' must run strictly after this one commits.
--
-- Purely additive to a 4-value enum with two known consumers
-- (prevention_risk_scores.tier, patient_risk_scores.risk_level) — no
-- existing row's value changes, so this cannot break any current CHECK,
-- policy, or comparison.

alter type public.risk_level add value 'unknown';
