-- S23 step 3: add scribe-related columns to clinical_encounter_notes
-- Links the encounter note to the consent that authorised the AI draft,
-- and adds the patient-facing summary generated by the same Claude call.

begin;

alter table public.clinical_encounter_notes
  add column if not exists scribe_consent_id uuid references public.scribe_consents(id) on delete restrict,
  add column if not exists patient_summary text,
  add column if not exists patient_summary_language text check (patient_summary_language in ('en-NG', 'pcm'));

comment on column public.clinical_encounter_notes.scribe_consent_id is
  'Which scribe consent authorised the AI draft. NULL for manually written notes.';
comment on column public.clinical_encounter_notes.patient_summary is
  'Plain-language visit summary in the patient''s language. Generated by the scribe-draft edge function, visible to the patient only after the clinician finalises the note.';
comment on column public.clinical_encounter_notes.patient_summary_language is
  'Language variant of the patient summary (en-NG or pcm).';

create index if not exists clinical_encounter_notes_scribe_consent_idx
  on public.clinical_encounter_notes(scribe_consent_id) where scribe_consent_id is not null;

-- ── closing assertions ──────────────────────────────────────────────

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'clinical_encounter_notes'
      and column_name = 'scribe_consent_id'
  ) then raise exception 'scribe_consent_id column not added'; end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'clinical_encounter_notes'
      and column_name = 'patient_summary'
  ) then raise exception 'patient_summary column not added'; end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'clinical_encounter_notes'
      and column_name = 'patient_summary_language'
  ) then raise exception 'patient_summary_language column not added'; end if;
end $$;

commit;
