-- Tarragon Health
-- Quarterly PDF report archive, shared by Family Premium and ParentCare —
-- both tiers' pricing.ts copy already promises a "quarterly PDF report",
-- but nothing implemented it before this migration (only Health Passport
-- PDF existed). Append-only, mirroring outcome_reports' posture, so a
-- family/parent can look back at past quarters rather than only ever
-- seeing a live re-render. Generated by a scheduled job (Vercel Cron ->
-- app/api/cron/generate-quarterly-reports), never by raw patient insert —
-- insert is service-role only.

create table public.patient_quarterly_reports (
  id                uuid primary key default gen_random_uuid(),
  patient_id        uuid not null references public.profiles (id) on delete cascade,
  organisation_id   uuid not null references public.organisations (id) on delete restrict,
  period_start      date not null,
  period_end        date not null,
  snapshot          jsonb not null,
  generated_at      timestamptz not null default now(),
  constraint patient_quarterly_reports_period_valid check (period_end >= period_start)
);

create index patient_quarterly_reports_patient_idx on public.patient_quarterly_reports (patient_id, period_end desc);
create index patient_quarterly_reports_org_idx on public.patient_quarterly_reports (organisation_id);

alter table public.patient_quarterly_reports enable row level security;

-- Select: the patient themselves, the plan_owner of a family_plan_members
-- row naming them (so a ParentCare/Family Premium subscriber can read their
-- parent's/family member's reports, same visibility they already have via
-- family_plan_members), or org-staff.
create policy patient_quarterly_reports_select on public.patient_quarterly_reports
  for select to authenticated
  using (
    patient_id = (select auth.uid())
    or exists (
      select 1 from public.family_plan_members fpm
      where fpm.member_id = patient_quarterly_reports.patient_id
        and fpm.plan_owner_id = (select auth.uid())
    )
    or private.is_org_staff(organisation_id)
  );

-- Insert: service-role only (the scheduled generation job) — never a raw
-- patient/staff insert, matching protocol_versions' append-only posture.
-- No insert policy for `authenticated` at all; service role bypasses RLS.

grant select on public.patient_quarterly_reports to authenticated;
