-- Tarragon Health — patient email when a medication is prescribed or a lab
-- test order is generated by the system/a doctor.
--
-- Founder requirement: whenever a medication is prescribed to a patient, OR a
-- lab test order/request is generated by the system or a doctor, the patient
-- must receive an email with the details of what was prescribed/requested.
--
-- Design mirrors private.enqueue_pharmacy_order_notifications (the existing
-- payment_confirmed → notifications pattern):
--   • both triggers are SECURITY DEFINER so they can read the patient's email
--     from auth.users (email lives there, not on profiles);
--   • recipient_id is always the patient (the column is NOT NULL → profiles);
--   • rows are enqueued into `notifications`, which the send-pending-
--     notifications Edge Function renders + delivers (email via Resend, with
--     per-row retry + graceful degradation when credentials are unset);
--   • email is the guaranteed channel the requirement asks for; a best-effort
--     WhatsApp row is enqueued alongside for parity with every other patient
--     notification (dispatcher falls back to SMS until the Meta template is
--     approved). Neither is a required interface — this is a notification/
--     confirmation layer only, squarely inside the WhatsApp-is-notifications
--     rule.
--
-- Scope decisions (matching the founder's wording exactly):
--   • Medications: only clinician/specialist-*prescribed* meds notify. A
--     patient who self-adds a medication (source = 'patient') already knows
--     about it, so no email is sent for those.
--   • Lab orders: EVERY lab order notifies the patient. A doctor/system-
--     generated order tells them a test was requested for them; a self-booked
--     order gives them a showable confirmation (order number + test name) to
--     present at the lab so it knows exactly what they ordered. The copy varies
--     on payload.self_booked.
-- New templates (medication_prescribed_patient, lab_order_requested_patient)
-- are added to the send-pending-notifications Edge Function in the same change;
-- until that function is redeployed, these rows render as "unknown template".

-- ---------------------------------------------------------------------------
-- 1. Medication prescribed → patient notification
-- ---------------------------------------------------------------------------
create or replace function private.enqueue_medication_prescribed_notifications()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_patient       public.profiles%rowtype;
  v_patient_email text;
  v_details       text;
begin
  -- Only a clinician/specialist prescription for an active drug is a "prescribed
  -- to the patient" event. Patient-authored (source = 'patient') rows are skipped.
  if new.source not in ('clinician', 'specialist') or new.is_active is not true then
    return new;
  end if;

  select * into v_patient from public.profiles where id = new.patient_id;
  select email into v_patient_email from auth.users where id = new.patient_id;

  -- Human summary, e.g. "Amlodipine 5mg, once daily".
  v_details := new.drug_name
    || coalesce(' ' || nullif(new.dose, ''), '')
    || coalesce(', ' || nullif(new.frequency, ''), '');

  -- Email — the required, guaranteed channel. Only if an address is on file.
  if v_patient_email is not null then
    insert into public.notifications
      (organisation_id, recipient_id, channel, status, template, payload)
    values (
      new.organisation_id, new.patient_id, 'email', 'pending',
      'medication_prescribed_patient',
      jsonb_build_object(
        'to_email',        v_patient_email,
        'patient_name',    coalesce(v_patient.full_name, 'there'),
        'drug_name',       new.drug_name,
        'dose',            coalesce(new.dose, ''),
        'frequency',       coalesce(new.frequency, ''),
        'details',         v_details,
        'prescriber_name', coalesce(new.prescriber_name, '')
      )
    );
  end if;

  -- Best-effort WhatsApp (SMS fallback) for parity with other patient nudges.
  insert into public.notifications
    (organisation_id, recipient_id, channel, status, template, payload)
  values (
    new.organisation_id, new.patient_id, 'whatsapp', 'pending',
    'medication_prescribed_patient',
    jsonb_build_object(
      'patient_name',    coalesce(v_patient.full_name, 'there'),
      'drug_name',       new.drug_name,
      'dose',            coalesce(new.dose, ''),
      'frequency',       coalesce(new.frequency, ''),
      'details',         v_details,
      'prescriber_name', coalesce(new.prescriber_name, '')
    )
  );

  return new;
end;
$$;

drop trigger if exists medications_enqueue_prescribed_notifications on public.medications;
create trigger medications_enqueue_prescribed_notifications
  after insert on public.medications
  for each row
  execute function private.enqueue_medication_prescribed_notifications();

-- ---------------------------------------------------------------------------
-- 2. Lab test order generated by system/doctor → patient notification
-- ---------------------------------------------------------------------------
create or replace function private.enqueue_lab_order_requested_notifications()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_patient       public.profiles%rowtype;
  v_patient_email text;
  v_test_name     text;
  v_order_ref     text;
  v_self_booked   boolean;
begin
  -- Every lab order notifies the patient. Self-booked orders get a showable
  -- confirmation to present at the lab; doctor/system orders get a "requested
  -- for you" message. The template branches on self_booked.
  v_self_booked := (new.origin = 'patient_initiated' and new.ordered_by is null);

  select * into v_patient from public.profiles where id = new.patient_id;
  select email into v_patient_email from auth.users where id = new.patient_id;

  select name into v_test_name from public.panel_bundles where id = new.panel_bundle_id;
  v_test_name := coalesce(v_test_name, 'a lab test');
  v_order_ref := coalesce(new.order_number, 'your order');

  -- Email — the required, guaranteed channel.
  if v_patient_email is not null then
    insert into public.notifications
      (organisation_id, recipient_id, channel, status, template, payload)
    values (
      new.organisation_id, new.patient_id, 'email', 'pending',
      'lab_order_requested_patient',
      jsonb_build_object(
        'to_email',     v_patient_email,
        'patient_name', coalesce(v_patient.full_name, 'there'),
        'order_number', v_order_ref,
        'test_name',    v_test_name,
        'self_booked',  v_self_booked
      )
    );
  end if;

  -- Best-effort WhatsApp (SMS fallback).
  insert into public.notifications
    (organisation_id, recipient_id, channel, status, template, payload)
  values (
    new.organisation_id, new.patient_id, 'whatsapp', 'pending',
    'lab_order_requested_patient',
    jsonb_build_object(
      'patient_name', coalesce(v_patient.full_name, 'there'),
      'order_number', v_order_ref,
      'test_name',    v_test_name,
      'self_booked',  v_self_booked
    )
  );

  return new;
end;
$$;

drop trigger if exists lab_orders_enqueue_requested_notifications on public.lab_orders;
create trigger lab_orders_enqueue_requested_notifications
  after insert on public.lab_orders
  for each row
  execute function private.enqueue_lab_order_requested_notifications();
