-- ---------------------------------------------------------------------------
-- The new lab_partner role leaves private.is_org_staff.
--
-- COMPOSED MIGRATION — read this header before editing.
--
-- This file originally shipped on the lab_partner branch timestamped
-- 20260727004500 and rewrote private.is_org_staff to exclude exactly
-- ('patient', 'pharmacist', 'lab_partner'). It was written before
-- 20260729124330 (I9) and 20260729194127 (scoped-access roles) existed, so
-- that role list was complete AT THE TIME and is dangerously incomplete now:
-- applying it as written would drop the corporate_admin/hmo_admin exclusion
-- (I9) and the lab_liaison/finance/analyst exclusion, silently re-admitting
-- five roles to 314 policies across 110 patient-scoped tables. It sorted
-- BEFORE both of those migrations by version despite being applied after
-- them in wall-clock time, so it would have won.
--
-- It has therefore been renumbered past 20260729194127 and rewritten to
-- COMPOSE with, rather than replace, the two hardenings that landed first.
-- The net change against the live function is one role: lab_partner.
--
-- Why lab_partner does not belong in is_org_staff, in its own right:
-- it is an employee of a PARTNER LAB, not of Tarragon. Its entire surface is
-- the three SECURITY DEFINER RPCs added in the surface migration
-- (lab_partner_orders, lab_partner_order_patient, lab_partner_upload_result),
-- each scoped to one lab via private.lab_partner_provider(). Those RPCs exist
-- specifically to confine cross-tenant PHI to the orders routed to that one
-- lab; blanket is_org_staff access is a silent bypass of the isolation they
-- were written to enforce. This is the same reasoning, and the same class of
-- bug, as pharmacist in 20260729194127 — and the same live exposure that was
-- confirmed there against a real pharmacist fixture reading a real lab_orders
-- row it had no business seeing.
--
-- The admin member-provisioning UI's "Organisation (optional)" field does not
-- distinguish by role, so a lab_partner account carrying a real
-- organisation_id is a realistic misconfiguration, not a contrived one.
-- ---------------------------------------------------------------------------

-- 1. Keep the role-class helper accurate ---------------------------------------
-- Defined in 20260729194127 to name the class once instead of spelling out a
-- role list in every policy that needs it. Nothing references it yet (verified:
-- zero policies, zero function bodies), but it is the documented definition of
-- "reaches its data through its own RPCs, not through care-team membership",
-- and lab_partner is now the clearest example of that class.
create or replace function private.is_scoped_access_role()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid())
      and role in ('pharmacist', 'lab_partner', 'lab_liaison', 'finance', 'analyst')
  );
$$;

comment on function private.is_scoped_access_role() is
  'True for a partner-employee (pharmacist, lab_partner) or back-office '
  '(lab_liaison, finance, analyst) account. Deliberately excluded from '
  'private.is_org_staff: each reaches its data through its own purpose-built '
  'SECURITY DEFINER RPCs or through a table re-granted to it by name, never '
  'through blanket care-team membership.';

-- 2. The single structural change ---------------------------------------------
-- Byte-identical to the live 20260729194127 definition except for lab_partner
-- in the partner/back-office exclusion list. Every patient-scoped policy in the
-- database inherits it, including the ~90 whose policies are generated by
-- format() loops (20260705211129) rather than written out.

create or replace function private.is_org_staff(org uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid())
      and role <> 'patient'
      -- I9: an institution administrator is not care-team staff.
      and role not in ('corporate_admin', 'hmo_admin')
      -- Nor is a partner employee or a back-office account. Excluded here
      -- rather than in 314 individual policies. lab_partner joins this list.
      and role not in ('pharmacist', 'lab_partner', 'lab_liaison', 'finance', 'analyst')
      and (role = 'admin' or organisation_id = org)
  );
$$;

comment on function private.is_org_staff(uuid) is
  'Tarragon care-team and operations staff for an organisation: clinician, '
  'doctor, care_coordinator, and the admin super-user. Institution admins '
  '(I9), partner employees (pharmacist, lab_partner) and back-office roles '
  'are excluded and are served by named grants or their own SECURITY DEFINER '
  'RPCs instead.';

-- 3. No re-grant for lab_partner -----------------------------------------------
-- Deliberately none. 20260729194127 re-granted two tables to lab_liaison by
-- name because that role's page reads them directly. lab_partner's page does
-- not touch a table at all — apps/web/src/lib/queries/lab-partner.ts and the
-- upload action are 100% .rpc(...) calls — so the exclusion above costs it
-- nothing. The assertion block below refuses to apply if that stops being true.

-- 4. Assertions ----------------------------------------------------------------

do $$
declare
  v_src    text;
  v_role   text;
  v_org    uuid;
  v_id     uuid;
  v_leaky  text;
  v_count  integer;
begin
  select prosrc into v_src
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'private' and p.proname = 'is_org_staff';

  -- The new exclusion took.
  if v_src not like '%lab_partner%' then
    raise exception 'is_org_staff was not rewritten with the lab_partner exclusion';
  end if;

  -- And — the entire point of renumbering this migration — none of the
  -- previously-landed exclusions were lost by this rewrite.
  if v_src not like '%corporate_admin%' then
    raise exception 'the I9 institution exclusion (20260729124330) was lost';
  end if;
  if v_src not like '%hmo_admin%' then
    raise exception 'the I9 hmo_admin exclusion (20260729124330) was lost';
  end if;
  foreach v_role in array array['pharmacist', 'lab_liaison', 'finance', 'analyst']
  loop
    if v_src not like '%' || v_role || '%' then
      raise exception
        'the scoped-access exclusion of % (20260729194127) was lost', v_role;
    end if;
  end loop;

  -- Prove behaviour, not text: every real account in any excluded partner or
  -- back-office role must now fail the predicate for its OWN organisation.
  for v_role, v_org, v_id in
    select p.role::text, p.organisation_id, p.id
    from public.profiles p
    where p.role::text in ('pharmacist', 'lab_partner', 'lab_liaison', 'finance', 'analyst')
      and p.organisation_id is not null
  loop
    if (select exists (
          select 1 from public.profiles
          where id = v_id and role <> 'patient'
            and role not in ('corporate_admin', 'hmo_admin')
            and role not in ('pharmacist', 'lab_partner', 'lab_liaison', 'finance', 'analyst')
            and (role = 'admin' or organisation_id = v_org)
        )) then
      raise exception 'a % account still satisfies the is_org_staff predicate', v_role;
    end if;
  end loop;

  -- Care-team staff must be UNAFFECTED. If this fires, the narrowing overshot
  -- and real clinical features are about to go blank.
  select p.organisation_id, p.id into v_org, v_id
  from public.profiles p
  where p.role::text in ('clinician', 'doctor', 'care_coordinator')
    and p.organisation_id is not null
  limit 1;

  if v_id is not null then
    if not (select exists (
          select 1 from public.profiles
          where id = v_id and role <> 'patient'
            and role not in ('corporate_admin', 'hmo_admin')
            and role not in ('pharmacist', 'lab_partner', 'lab_liaison', 'finance', 'analyst')
            and (role = 'admin' or organisation_id = v_org)
        )) then
      raise exception 'a care-team account no longer satisfies is_org_staff — narrowing overshot';
    end if;
  end if;

  -- The whole argument for granting lab_partner nothing is that its surface is
  -- served exclusively by SECURITY DEFINER functions, which ignore RLS. If any
  -- of them is not, this migration silently breaks the role's dashboard.
  select string_agg(p.proname, ', '), count(*)
    into v_leaky, v_count
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and p.proname like 'lab\_partner\_%'
    and not p.prosecdef;

  if v_count > 0 then
    raise exception
      'these lab_partner RPCs are not SECURITY DEFINER and would break once '
      'the role loses is_org_staff: %', v_leaky;
  end if;

  -- All three must exist, or the role has no access path left at all.
  if (select count(*) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
      where n.nspname = 'public' and p.proname like 'lab\_partner\_%') <> 3 then
    raise exception 'expected exactly 3 public.lab_partner_* RPCs';
  end if;

  -- And the gate they are all scoped through.
  if not exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                 where n.nspname = 'private' and p.proname = 'lab_partner_provider') then
    raise exception 'private.lab_partner_provider() is missing — lab_partner has no scoping gate';
  end if;

  -- The lab-liaison re-grants from 20260729194127 must survive untouched: this
  -- migration does not recreate those policies, so if they are gone, something
  -- else dropped them and the liaison page is broken.
  if (select count(*) from pg_policies
      where schemaname = 'public'
        and tablename in ('profiles', 'lab_result_documents')
        and coalesce(qual, with_check) like '%is_lab_liaison%') <> 2 then
    raise exception 'the lab-liaison policies from 20260729194127 are no longer both present';
  end if;
end $$;
