-- Tarragon Health — five new Diabetes-category articles for the /resources
-- hub, giving the "Explore more Diabetes Management resources" carousel
-- (apps/web/src/app/(marketing)/_components/resource-carousel.tsx) real
-- depth on both /resources and /diabetes: first-90-days, Nigerian-kitchen
-- nutrition, non-medical-treatment myths, mental health, and day-to-day
-- routine. Same idempotent insert-only shape as the original seven
-- (20260723121000_marketing_resources.sql); the static
-- _content/resources.ts fallback carries identical copy.

insert into public.marketing_resources
  (slug, title, description, category, read_minutes, related_href, related_label, sections, is_published, sort_order)
values
('diabetes-just-diagnosed', 'So you''ve just been diagnosed with diabetes. Now what?', 'The first week, the questions worth asking your doctor, and what actually changes versus what doesn''t.', 'Diabetes', 5, '/diabetes', 'Diabetes care at Tarragon', '[{"heading":"Take a breath first","paragraphs":["A new diabetes diagnosis can feel like a lot at once. It is not an emergency that demands you overhaul your entire life today. It is a starting line: you now have information that lets you and a doctor act, and that is better than not knowing."]},{"heading":"What actually needs to happen this week","paragraphs":["Your doctor will confirm the type (type 1, type 2, or gestational, if you are pregnant), because that changes the plan. Expect baseline tests beyond the sugar result itself: HbA1c, kidney function, cholesterol, and blood pressure, plus a referral for an eye check. If a medicine is prescribed, start it as instructed even before you have mastered the diet side; the two work together, not in sequence."]},{"heading":"Questions worth taking to your first proper review","paragraphs":["What is my HbA1c and what target are we aiming for? Do I need medication now, or are we starting with lifestyle change first? What symptoms mean I should call sooner rather than wait for the next appointment? When is my next check, and what will it look at?"]},{"heading":"What changes, and what genuinely doesn''t","paragraphs":["You can still eat foods you love, in sensible portions; still travel; still work as before. What changes is a new habit of checking in on your body on a schedule rather than only when something feels wrong. Most people with type 2 diabetes who follow their plan consistently live long, ordinary lives; the complications people fear come from years of unmanaged sugar, not from the diagnosis itself."]}]'::jsonb, true, 21),
('diabetes-diet-nigerian-kitchen', 'Diabetes and your plate: what to eat in a Nigerian kitchen', 'There is no forbidden food list, only portion, pairing, and a few swaps that make the biggest difference.', 'Diabetes', 5, '/diabetes', 'Diabetes care at Tarragon', '[{"heading":"No food is banned outright","paragraphs":["Eba, pounded yam, rice, and other everyday staples don''t have to disappear from your table. What matters most is portion size and what you eat them alongside; a smaller starchy portion next to more protein and vegetables behaves very differently in your body than a large one eaten alone."]},{"heading":"Carbohydrates that behave better","paragraphs":["Less-processed, higher-fibre carbohydrates raise sugar more slowly: unripe plantain rather than very ripe, brown rice or a smaller white-rice portion, and beans or other legumes as a base rather than a side. Fibre-rich vegetables (ugu, waterleaf, okra) let you build a fuller plate without much sugar impact."]},{"heading":"The order you eat in matters too","paragraphs":["Eating vegetables and protein before the starchy part of a meal genuinely blunts the sugar rise that follows. In practice: a slightly smaller soup/stew starch component, more fish, chicken, or beans, and vegetables eaten first rather than last."]},{"heading":"What''s actually worth cutting back","paragraphs":["Sugary zobo, soft drinks, and table sugar in tea add sugar with no fibre to slow it down; deep-fried foods and packaged snacks add the kind of fat that works against your numbers over time. Small, consistent swaps you can keep up beat one dramatic overhaul that lasts a fortnight."]}]'::jsonb, true, 42),
('diabetes-non-medical-treatments-do-they-work', 'Non-medical diabetes treatments: do they really work?', 'What the evidence actually shows about herbal remedies, and why the real danger is stopping what works.', 'Diabetes', 4, '/diabetes', 'Diabetes care at Tarragon', '[{"heading":"Why this question matters here","paragraphs":["Herbal remedies (bitter leaf, moringa, aloe vera, cinnamon, and others) are widely marketed in Nigeria as diabetes cures. Some people stop their prescribed medicine to try them instead. That decision, not the herb itself, is usually where the real harm happens."]},{"heading":"What the evidence actually shows","paragraphs":["A few of these (cinnamon and bitter melon among them) show a small effect on blood sugar in some studies. Small is the operative word: nowhere close to replacing medication for someone already diagnosed, and outside a laboratory there is no way to know the dose or purity of what you''re actually taking."]},{"heading":"The real risk isn''t trying them, it''s stopping what works","paragraphs":["Never replace a prescribed diabetes medicine with a herbal product without your doctor knowing. Tell your care team about anything you''re taking alongside your prescription; some herbal products interact with medication in ways that are hard to predict on your own."]},{"heading":"What genuinely does earn its place","paragraphs":["Food choices, movement, weight, and sleep are not the exciting answer, but they are the proven one: real, repeated evidence shows they measurably lower blood sugar over time. The honest message is that there is no shortcut supplement, but the boring, unglamorous changes genuinely work."]}]'::jsonb, true, 43),
('diabetes-and-mental-health', 'Diabetes and mental health: why the emotional side matters too', 'Diabetes distress, the two-way link with depression, and why asking for support is good diabetes care.', 'Diabetes', 4, '/diabetes', 'Diabetes care at Tarragon', '[{"heading":"Diabetes distress is real, and common","paragraphs":["Living with a condition that asks for daily attention, checking sugar, timing meals, taking medicine on schedule, is genuinely tiring. Frustration, guilt after a ''bad'' reading, and burnout from the routine are common enough to have a name: diabetes distress. It overlaps with depression but isn''t quite the same thing."]},{"heading":"The two-way link with depression","paragraphs":["People living with diabetes have a higher risk of depression, and depression makes diabetes harder to manage, motivation for daily self-care tends to drop when mood is low. Each can quietly worsen the other, so treating the sugar numbers without noticing the mood behind them can stall progress that looks otherwise unexplained."]},{"heading":"Signs worth mentioning to your care team","paragraphs":["Persistent low mood, losing interest in things you used to enjoy, feeling like checking your sugar or taking medicine is pointless, or sleep and appetite changes lasting more than two weeks are all worth raising, even if they feel unrelated to diabetes itself."]},{"heading":"This is not a personal failing","paragraphs":["A high HbA1c is not a report card on your character. Good diabetes care treats the numbers and the person behind them together, and asking for support with the emotional weight of a chronic condition is itself part of managing it well, not a separate, lesser concern."]}]'::jsonb, true, 44),
('diabetes-day-to-day-management', 'Managing your diabetes day to day: monitoring, medicine and routine', 'Why consistency beats perfection, what daily readings and HbA1c each tell you, and the follow-up habit that matters most.', 'Diabetes', 5, '/diabetes', 'Diabetes care at Tarragon', '[{"heading":"Build a routine, not a perfect day","paragraphs":["The goal isn''t a flawless day; it''s a repeatable one. Roughly consistent meal times and a fixed time for medicine turn diabetes care into a habit rather than a decision you have to make from scratch every day, which is where consistency quietly comes from."]},{"heading":"Monitoring: what each check actually tells you","paragraphs":["A home glucose check, if your doctor has prescribed one, shows today''s number: useful, but a single snapshot. HbA1c, done every three to six months, shows the bigger three-month trend. They answer different questions; neither replaces the other."]},{"heading":"Medicine: consistency beats perfection","paragraphs":["Take medicine on schedule even on a day you''ve eaten well and feel fine. Missed doses are one of the most common, and most preventable, reasons control slips. A phone reminder tied to an existing daily habit works better than relying on memory alone."]},{"heading":"The follow-up habit that changes outcomes","paragraphs":["People who do best treat diabetes as an ongoing conversation with their care team rather than a one-time lecture at diagnosis. Regular reviews catch drift before it becomes a complication, and the plan gets adjusted as life changes, a new job, a pregnancy, a change in weight, instead of staying frozen from day one."]}]'::jsonb, true, 41)
on conflict (slug) do nothing;
