-- Tarragon Health — Care Management Engine, step 6a
--
-- Spec §3.13: "The engine should identify: missed monitoring, missed
-- appointments, abnormal results, non-adherence, overdue tests, failed
-- referrals... These become exceptions. The care team manages exceptions
-- rather than manually checking every patient."
--
-- care_outreach_tasks + private.queue_care_outreach() already IS this
-- platform's exception worklist (it covers missed monitoring, overdue
-- screening, and unactioned abnormal results today) — the right move is to
-- extend it, not build a second, competing "exceptions" table the care team
-- would have to check separately (this codebase has already made that
-- mistake once: care_outreach_tasks and care_plan_review_prompts overlap on
-- missed-medication today with no unification). This adds the one missing
-- trigger type a real care_tasks table now makes possible: a task the
-- patient (or another owner) never completed.
--
-- STANDALONE migration: ALTER TYPE ... ADD VALUE cannot be used in the same
-- transaction it runs in (same discipline as
-- 20260716223124_chronic_condition_enum.sql / 20260803125550). The function
-- that actually reads this new value lives in the next migration.

alter type public.outreach_trigger_type add value if not exists 'missed_care_task';
