/**
 * Renders the BPC course into (1) the seed migration and (2) the long-form audio scripts, from `bpc-course.ts`.
 * Pure: no file access. `bpc-seed.test.ts` writes the files when UPDATE_BPC_SEED=1 and otherwise fails if they drifted.
 *
 * Safety shape of the seed (docs/design/S33.md section 3):
 *   - every lesson is inserted as `draft`, so it is invisible until the CMO moves it through clinical review;
 *   - no reviewer name, no `clinician_reviewed`, no approval is written;
 *   - the course programme is inserted inactive and STAYS inactive: the older programme functions check only that flag and would
 *     serve its drafts. The course is read through `learning_course()`, which checks every lesson;
 *   - English only (founder decision D-14, 2026-10-07): no translation row is ever written.
 */
import { BPC_LESSONS, BPC_PROGRAMME, type BpcLesson, type LessonText } from "./bpc-course";

export const SEED_MIGRATION_FILE = "20261006193240_s33_bpc_course_seed.sql";
export const LONG_FORM_SCRIPTS_FILE = "long-form-scripts.json";
export const SEED_EVIDENCE_SOURCE = "WHO HEARTS technical package (themes only). Wording drafted for clinical review; not yet reviewed.";
export const SEED_AUTHOR = "Tarragon content team (draft for clinical review)";

/** Spoken at the end of a lesson recording, before the action. */
export const TRY_THIS_TODAY = "Try this today." as const;

const RECORDED_WORDS_PER_MINUTE = 100;

const words = (s: string): number => s.split(/\s+/).filter(Boolean).length;
export const estimatedMinutes = (body: string): number => Math.max(1, Math.ceil(words(body) / RECORDED_WORDS_PER_MINUTE));

const lit = (s: string): string => {
  if (s.includes("$bpc$")) throw new Error("text contains the dollar-quote tag");
  return `$bpc$${s}$bpc$`;
};

const checkJson = (c: LessonText["check"]): string =>
  JSON.stringify([{ question: c.question, options: [...c.options], answer_index: c.answerIndex }]);

/** What a lesson recording says: title, body, then the one action. The on-screen transcript is the same words. */
export function spokenScript(t: LessonText): string {
  return `${t.title}.\n\n${t.body}\n\n${TRY_THIS_TODAY} ${t.nextAction}`;
}

// NOTE: the header comment below still mentions Pidgin on purpose. This migration was applied to production before the English-only
// decision (D-14) and an applied migration is never edited; the output must stay byte-identical to the applied file.
export function renderBpcSeedSql(lessons: readonly BpcLesson[] = BPC_LESSONS): string {
  const out: string[] = [];
  out.push(`-- S33: seed for the blood pressure care course (BPC-01 to BPC-14). GENERATED by packages/i18n/src/bpc-seed.ts from
-- packages/i18n/src/bpc-course.ts (run: UPDATE_BPC_SEED=1 pnpm --filter @tarragon/i18n test bpc-seed). Do not edit by hand.
--
-- DRAFT CONTENT. Every lesson is inserted as 'draft' (invisible), the programme is inserted inactive, and no reviewer, review date or
-- approval is written. A lesson reaches a patient only after the CMO moves it draft -> clinical_review -> approved -> published and sets
-- next_review_due (learning_course() will not serve a lesson with no review date). Pidgin rows exist only for released clip ids
-- (audio/source/pcm-released.json); today none, so English is served.
--
-- Counts before this migration (live, 2026-10-06): no programme with code '${BPC_PROGRAMME.code}'; no content code starting 'bpc_'.
`);
  out.push(`insert into public.health_education_programmes (code, title, description, condition, category, is_active, sort_order)
values (${lit(BPC_PROGRAMME.code)}, ${lit(BPC_PROGRAMME.title)}, ${lit(BPC_PROGRAMME.description)}, 'hypertension', 'hypertension', false, 30)
on conflict (code) do nothing;
`);
  out.push(`insert into public.health_education_content
  (code, title, summary, body, content_type, estimated_minutes, condition, category, reading_level, knowledge_check, sort_order,
   content_status, clinician_reviewed, audio_clip_id, next_action, evidence_source, author_name, topic_group_code)
values`);
  const rows = lessons.map((l, i) => {
    const t = l.en;
    return `  (${lit(l.slug)}, ${lit(t.title)}, ${lit(t.summary)}, ${lit(t.body)}, 'article', ${estimatedMinutes(t.body)}, 'hypertension', 'hypertension', 'simple', ${lit(checkJson(t.check))}::jsonb, ${200 + i}, 'draft', false, ${lit(l.code)}, ${lit(t.nextAction)}, ${lit(SEED_EVIDENCE_SOURCE)}, ${lit(SEED_AUTHOR)}, ${lit(BPC_PROGRAMME.code)})`;
  });
  out.push(rows.join(",\n") + "\non conflict (code) do nothing;\n");

  out.push(`insert into public.health_education_programme_modules (programme_id, content_id, module_number, title)
select p.id, c.id, m.module_number, c.title
from public.health_education_programmes p
join (values
${lessons.map((l, i) => `  (${lit(BPC_PROGRAMME.code)}, ${lit(l.slug)}, ${i + 1})`).join(",\n")}
) as m(programme_code, content_code, module_number) on m.programme_code = p.code
join public.health_education_content c on c.code = m.content_code
on conflict (programme_id, module_number) do nothing;
`);

  out.push(`do $$
declare
  v_modules integer;
begin
  select count(*) into v_modules
    from public.health_education_programme_modules m
    join public.health_education_programmes p on p.id = m.programme_id
    where p.code = ${lit(BPC_PROGRAMME.code)};
  if v_modules <> ${lessons.length} then
    raise exception 'BPC seed: expected ${lessons.length} modules, found %', v_modules;
  end if;
  if exists (select 1 from public.health_education_content where topic_group_code = ${lit(BPC_PROGRAMME.code)} and (is_active or clinician_reviewed or content_status <> 'draft' or reviewed_by_name is not null)) then
    raise exception 'BPC seed: a seeded lesson is visible or carries a review record';
  end if;
  if exists (select 1 from public.health_education_programmes where code = ${lit(BPC_PROGRAMME.code)} and is_active) then
    raise exception 'BPC seed: the course programme must start inactive';
  end if;
end $$;
`);
  return out.join("\n");
}

export interface LongFormScript {
  readonly en: string;
}

/** Scripts for the audio importer (`scripts/audio/import-production-list.py`). */
export function renderLongFormScripts(
  lessons: readonly BpcLesson[] = BPC_LESSONS,
  extra: Readonly<Record<string, LongFormScript>> = {},
): string {
  const scripts: Record<string, LongFormScript> = {};
  for (const l of lessons) scripts[l.code] = { en: spokenScript(l.en) };
  for (const [id, s] of Object.entries(extra)) scripts[id] = s;
  const sorted = Object.fromEntries(Object.entries(scripts).sort(([a], [b]) => a.localeCompare(b)));
  return JSON.stringify(sorted, null, 2) + "\n";
}
