import { describe, expect, it } from "@jest/globals";
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { en } from "./en";
import { pcm } from "./pcm";
import { HELD_IN_ENGLISH, type HeldReason } from "./held-in-english";

/**
 * "No untranslated keys" made checkable. A key whose Pidgin equals its English is allowed only if it is on the ledger
 * (held-in-english.ts) with a reason. A NEW identical key fails this test until someone adds it on purpose
 * (UPDATE_HELD_LEDGER=1 regenerates the file, so the addition shows in the diff). A ledger entry whose Pidgin has since
 * been written fails too, so the ledger only shrinks as native review lands.
 */
const STAFF = /^(console|golive|scribe|titration|credential|quality|admin|notify)\./;
const CLINICAL = /^(triage\.|wq\.red_flag\.|breathing\.safety_|breathing\.keep_medicines)/;
const wordCount = (s: string): number => s.replace(/\{\w+\}/g, "").split(/\s+/).filter(Boolean).length;

export function classify(key: string, value: string): HeldReason {
  if (STAFF.test(key)) return "staff_facing";
  if (CLINICAL.test(key)) return "clinical_safety_held";
  if (wordCount(value) <= 4) return "short_common_word";
  return "awaiting_native_review";
}

const identical = (Object.keys(en) as (keyof typeof en)[]).filter((k) => en[k] === pcm[k]);

describe("Pidgin held in English", () => {
  it("is on the ledger, and the ledger holds nothing that has been translated", () => {
    if (process.env.UPDATE_HELD_LEDGER === "1") {
      const here = dirname(fileURLToPath(import.meta.url));
      const lines = identical.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(classify(k, en[k]))},`);
      writeFileSync(
        resolve(here, "held-in-english.ts"),
        `/**
 * Every key whose Pidgin is the same as its English, and why. GENERATED by held-in-english.test.ts
 * (UPDATE_HELD_LEDGER=1 pnpm --filter @tarragon/i18n test held-in-english); do not edit by hand.
 *
 * staff_facing: shown only to staff, who work in English.
 * clinical_safety_held: wording the CMO must sign and a native speaker must review first (OQ-19, OQ-87, OQ-74).
 * short_common_word: a word or label that Nigerian Pidgin uses as it is (Vitals, Messages, Cancel).
 * awaiting_native_review: a sentence nobody has written Pidgin for yet; the debt this ledger exists to show.
 */
export type HeldReason = "staff_facing" | "clinical_safety_held" | "short_common_word" | "awaiting_native_review";

export const HELD_IN_ENGLISH: Readonly<Record<string, HeldReason>> = {
${lines.join("\n")}
};
`,
      );
    }
    const missing = identical.filter((k) => !(k in HELD_IN_ENGLISH));
    const stale = Object.keys(HELD_IN_ENGLISH).filter((k) => !(k in en) || en[k as keyof typeof en] !== pcm[k as keyof typeof pcm]);
    expect({ missing, stale }).toEqual({ missing: [], stale: [] });
  });

  it("keeps the reason honest: a held key carries the reason the rules give it", () => {
    const wrong = identical.filter((k) => HELD_IN_ENGLISH[k] !== classify(k, en[k]));
    expect(wrong).toEqual([]);
  });

  it("never lets the course or breathing strings sit in the debt bucket", () => {
    const debt = identical.filter((k) => /^(course|lesson|breathing)\./.test(k) && HELD_IN_ENGLISH[k] === "awaiting_native_review");
    expect(debt).toEqual([]);
  });
});
